'From Cuis 4.1 of 12 December 2012 [latest update: #1583] on 29 January 2013 at 10:08:49 pm'!
'Description Add-Ons which show how Morphic works'!
!classDefinition: #LayoutDemo0 category: #'Add-Ons-LayoutDemo'!
SystemWindow subclass: #LayoutDemo0
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Add-Ons-LayoutDemo'!
!classDefinition: 'LayoutDemo0 class' category: #'Add-Ons-LayoutDemo'!
LayoutDemo0 class
	instanceVariableNames: ''!

!classDefinition: #LayoutDemo1 category: #'Add-Ons-LayoutDemo'!
SystemWindow subclass: #LayoutDemo1
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Add-Ons-LayoutDemo'!
!classDefinition: 'LayoutDemo1 class' category: #'Add-Ons-LayoutDemo'!
LayoutDemo1 class
	instanceVariableNames: ''!

!classDefinition: #LayoutDemo1b category: #'Add-Ons-LayoutDemo'!
SystemWindow subclass: #LayoutDemo1b
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Add-Ons-LayoutDemo'!
!classDefinition: 'LayoutDemo1b class' category: #'Add-Ons-LayoutDemo'!
LayoutDemo1b class
	instanceVariableNames: ''!

!classDefinition: #LayoutDemo2 category: #'Add-Ons-LayoutDemo'!
SystemWindow subclass: #LayoutDemo2
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Add-Ons-LayoutDemo'!
!classDefinition: 'LayoutDemo2 class' category: #'Add-Ons-LayoutDemo'!
LayoutDemo2 class
	instanceVariableNames: ''!

!classDefinition: #LayoutDemo2b category: #'Add-Ons-LayoutDemo'!
SystemWindow subclass: #LayoutDemo2b
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Add-Ons-LayoutDemo'!
!classDefinition: 'LayoutDemo2b class' category: #'Add-Ons-LayoutDemo'!
LayoutDemo2b class
	instanceVariableNames: ''!

!classDefinition: #LayoutDemo2c category: #'Add-Ons-LayoutDemo'!
SystemWindow subclass: #LayoutDemo2c
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Add-Ons-LayoutDemo'!
!classDefinition: 'LayoutDemo2c class' category: #'Add-Ons-LayoutDemo'!
LayoutDemo2c class
	instanceVariableNames: ''!

!classDefinition: #LayoutDemo2d category: #'Add-Ons-LayoutDemo'!
SystemWindow subclass: #LayoutDemo2d
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Add-Ons-LayoutDemo'!
!classDefinition: 'LayoutDemo2d class' category: #'Add-Ons-LayoutDemo'!
LayoutDemo2d class
	instanceVariableNames: ''!

!classDefinition: #LayoutDemo2e category: #'Add-Ons-LayoutDemo'!
SystemWindow subclass: #LayoutDemo2e
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Add-Ons-LayoutDemo'!
!classDefinition: 'LayoutDemo2e class' category: #'Add-Ons-LayoutDemo'!
LayoutDemo2e class
	instanceVariableNames: ''!

!classDefinition: #LayoutDemo3 category: #'Add-Ons-LayoutDemo'!
SystemWindow subclass: #LayoutDemo3
	instanceVariableNames: 'contentArea'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Add-Ons-LayoutDemo'!
!classDefinition: 'LayoutDemo3 class' category: #'Add-Ons-LayoutDemo'!
LayoutDemo3 class
	instanceVariableNames: ''!

!classDefinition: #LayoutDemo4 category: #'Add-Ons-LayoutDemo'!
SystemWindow subclass: #LayoutDemo4
	instanceVariableNames: 'contentArea'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Add-Ons-LayoutDemo'!
!classDefinition: 'LayoutDemo4 class' category: #'Add-Ons-LayoutDemo'!
LayoutDemo4 class
	instanceVariableNames: ''!

!classDefinition: #LayoutDemo4b category: #'Add-Ons-LayoutDemo'!
SystemWindow subclass: #LayoutDemo4b
	instanceVariableNames: 'contentArea'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Add-Ons-LayoutDemo'!
!classDefinition: 'LayoutDemo4b class' category: #'Add-Ons-LayoutDemo'!
LayoutDemo4b class
	instanceVariableNames: ''!

!classDefinition: #LayoutDemo5 category: #'Add-Ons-LayoutDemo'!
SystemWindow subclass: #LayoutDemo5
	instanceVariableNames: 'contentArea currentPage pages'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Add-Ons-LayoutDemo'!
!classDefinition: 'LayoutDemo5 class' category: #'Add-Ons-LayoutDemo'!
LayoutDemo5 class
	instanceVariableNames: ''!

!classDefinition: #LayoutDemo6 category: #'Add-Ons-LayoutDemo'!
SystemWindow subclass: #LayoutDemo6
	instanceVariableNames: 'contentArea currentPage pages'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Add-Ons-LayoutDemo'!
!classDefinition: 'LayoutDemo6 class' category: #'Add-Ons-LayoutDemo'!
LayoutDemo6 class
	instanceVariableNames: ''!

!classDefinition: #LayoutDemo6b category: #'Add-Ons-LayoutDemo'!
SystemWindow subclass: #LayoutDemo6b
	instanceVariableNames: 'contentArea currentPage pages'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Add-Ons-LayoutDemo'!
!classDefinition: 'LayoutDemo6b class' category: #'Add-Ons-LayoutDemo'!
LayoutDemo6b class
	instanceVariableNames: ''!

!classDefinition: #LayoutDemo6c category: #'Add-Ons-LayoutDemo'!
SystemWindow subclass: #LayoutDemo6c
	instanceVariableNames: 'contentArea currentPage pages'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Add-Ons-LayoutDemo'!
!classDefinition: 'LayoutDemo6c class' category: #'Add-Ons-LayoutDemo'!
LayoutDemo6c class
	instanceVariableNames: ''!

!classDefinition: #LayoutDemo6d category: #'Add-Ons-LayoutDemo'!
SystemWindow subclass: #LayoutDemo6d
	instanceVariableNames: 'contentArea currentPage pages'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Add-Ons-LayoutDemo'!
!classDefinition: 'LayoutDemo6d class' category: #'Add-Ons-LayoutDemo'!
LayoutDemo6d class
	instanceVariableNames: ''!

!classDefinition: #LayoutDemo7 category: #'Add-Ons-LayoutDemo'!
SystemWindow subclass: #LayoutDemo7
	instanceVariableNames: 'contentArea currentPage pages'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Add-Ons-LayoutDemo'!
!classDefinition: 'LayoutDemo7 class' category: #'Add-Ons-LayoutDemo'!
LayoutDemo7 class
	instanceVariableNames: ''!

!classDefinition: #LayoutDemo8Timer category: #'Add-Ons-LayoutDemo'!
SystemWindow subclass: #LayoutDemo8Timer
	instanceVariableNames: 'minuteMorphs startTime'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Add-Ons-LayoutDemo'!
!classDefinition: 'LayoutDemo8Timer class' category: #'Add-Ons-LayoutDemo'!
LayoutDemo8Timer class
	instanceVariableNames: ''!


!LayoutDemo0 commentStamp: 'hjh 1/16/2013 06:19' prior: 0!
Subclass of SystemWindow. 

Shows how to start building a GUI.
Just sets the window label.

      LayoutDemo0 new openInWorld!

!LayoutDemo1 commentStamp: 'hjh 1/16/2013 06:34' prior: 0!
Subclass of SystemWindow specialised to show how content has to be added.


A SystemWindow instance holds a LayoutMorph instance to which the content has to be added.

This class shows how to do that.



    LayoutDemo1 new openInWorld!

!LayoutDemo1b commentStamp: 'hjh 1/16/2013 06:34' prior: 0!
Subclass of SystemWindow specialised to show how content has to be added.


A SystemWindow instance holds a LayoutMorph instance to which the content has to be added.

This class shows how to do that.



    LayoutDemo1b new openInWorld!

!LayoutDemo2 commentStamp: 'hjh 1/16/2013 07:03' prior: 0!
Subclass of SystemWindow specialised to show how content has to be added.


   This class shows how to use the #addMorphUseAll: method to use all up the remaining space.



    LayoutDemo2 new openInWorld!

!LayoutDemo2b commentStamp: 'hjh 1/16/2013 07:03' prior: 0!
Subclass of SystemWindow specialised to show how content has to be added.


   This class shows how to use the #addMorphUseAll: method to use all up the remaining space.



    LayoutDemo2b new openInWorld!

!LayoutDemo2c commentStamp: 'hjh 1/16/2013 11:19' prior: 0!
Subclass of SystemWindow specialised to show how content has to be added.


   This class shows how to use the #addMorphUseAll: method to use all up the remaining space.

   In addition 
     self beRow.
   is used to put the morphs which are added into a row.



    LayoutDemo2c new openInWorld!

!LayoutDemo2d commentStamp: 'hjh 1/16/2013 11:07' prior: 0!
Subclass of SystemWindow specialised to show how content has to be added.


   This class shows how to use the #addMorphUseAll: method to use all up the remaining space. It as well demonstrates the use of UpdatingStringMorph. They may be used to build a specialized expression watch window.



    LayoutDemo2d new openInWorld!

!LayoutDemo2e commentStamp: 'hjh 1/16/2013 11:07' prior: 0!
Subclass of SystemWindow specialised to show how content has to be added.


   This class shows how to use the #addMorphUseAll: method to use all up the remaining space. It as well demonstrates the use of UpdatingStringMorph. They may be used to build a specialized expression watch window.



    LayoutDemo2e new openInWorld!

!LayoutDemo3 commentStamp: 'hjh 1/16/2013 09:35' prior: 0!
Subclass of SystemWindows specialised to display layout examples

    LayoutDemo3 new openInWorld!

!LayoutDemo4 commentStamp: 'hjh 1/16/2013 09:35' prior: 0!
Subclass of SystemWindows specialised to display layout examples

    LayoutDemo4 new openInWorld!

!LayoutDemo4b commentStamp: 'hjh 1/16/2013 13:07' prior: 0!
Subclass of SystemWindows specialised to display layout examples
Changed from LayoutDemo4: method 
    #makePages
    LayoutDemo4b new openInWorld!

!LayoutDemo5 commentStamp: 'hjh 1/16/2013 14:04' prior: 0!
Subclass of SystemWindows specialised to display layout examples


     LayoutDemo5 new openInWorld!

!LayoutDemo6 commentStamp: '<historical>' prior: 0!
Subclass of SystemWindows specialised to display layout examples

     LayoutDemo6 new openInWorld!

!LayoutDemo6b commentStamp: '<historical>' prior: 0!
Subclass of SystemWindows specialised to display layout examples

     LayoutDemo6b new openInWorld!

!LayoutDemo6c commentStamp: '<historical>' prior: 0!
Subclass of SystemWindows specialised to display layout examples

     LayoutDemo6c new openInWorld!

!LayoutDemo6d commentStamp: '<historical>' prior: 0!
Subclass of SystemWindows specialised to display layout examples

     LayoutDemo6d new openInWorld!

!LayoutDemo7 commentStamp: '<historical>' prior: 0!
Subclass of SystemWindows specialised to display layout examples

     LayoutDemo7 new openInWorld!

!LayoutDemo8Timer commentStamp: 'hjh 1/29/2013 18:57' prior: 0!
Subclass of SystemWindow specialised to display layout examples

     LayoutDemo8Timer new openInWorld!

!LayoutDemo0 methodsFor: 'GUI building' stamp: 'hjh 1/16/2013 06:22'!
buildMorphicWindow


     self setLabel: self className

	! !

!LayoutDemo0 methodsFor: 'initialization' stamp: 'hjh 1/16/2013 06:16'!
initialize

	super initialize.
	
	self buildMorphicWindow.! !

!LayoutDemo1 methodsFor: 'GUI building' stamp: 'hjh 1/16/2013 06:30'!
buildMorphicWindow


     	self setLabel: self className.

	self layoutMorph  addMorph: 
	   (RectangleLikeMorph new color: Color yellow) fixedHeight: 80.
	
 	self layoutMorph  addMorph: 
	   (RectangleLikeMorph new color: Color green) fixedHeight: 80.
 
	self layoutMorph  addMorph: 
	   (RectangleLikeMorph new color: Color red) fixedHeight: 80! !

!LayoutDemo1 methodsFor: 'initialization' stamp: 'hjh 1/16/2013 06:20'!
initialize

	super initialize.
	
	self buildMorphicWindow.! !

!LayoutDemo1b methodsFor: 'GUI building' stamp: 'hjh 1/16/2013 06:37'!
buildMorphicWindow


     	self setLabel: self className.

      self layoutMorph beRow.
     "or
      self beRow."

	self layoutMorph  addMorph: 
	   (RectangleLikeMorph new color: Color yellow) fixedHeight: 80.
	
 	self layoutMorph  addMorph: 
	   (RectangleLikeMorph new color: Color green) fixedHeight: 80.
 
	self layoutMorph  addMorph: 
	   (RectangleLikeMorph new color: Color red) fixedHeight: 80! !

!LayoutDemo1b methodsFor: 'initialization' stamp: 'hjh 1/16/2013 06:20'!
initialize

	super initialize.
	
	self buildMorphicWindow.! !

!LayoutDemo2 methodsFor: 'GUI building' stamp: 'hjh 1/16/2013 06:57'!
buildMorphicWindow


     	self setLabel: self className.

	self layoutMorph  addMorph: 
	   (RectangleLikeMorph new color: Color yellow) fixedHeight: 80.
	
 	self layoutMorph  addMorphUseAll: 
	   (RectangleLikeMorph new color: Color green) 
 
	! !

!LayoutDemo2 methodsFor: 'initialization' stamp: 'hjh 1/16/2013 06:20'!
initialize

	super initialize.
	
	self buildMorphicWindow.! !

!LayoutDemo2b methodsFor: 'GUI building' stamp: 'hjh 1/16/2013 11:02'!
buildMorphicWindow


     	self setLabel: self className.

	self layoutMorph  addMorphUseAll: 
	   (RectangleLikeMorph new color: Color red).

	self layoutMorph  addMorphUseAll: 
	   (RectangleLikeMorph new color: Color yellow).
	
 	self layoutMorph  addMorphUseAll: 
	   (RectangleLikeMorph new color: Color green) 
 
	! !

!LayoutDemo2b methodsFor: 'initialization' stamp: 'hjh 1/16/2013 06:20'!
initialize

	super initialize.
	
	self buildMorphicWindow.! !

!LayoutDemo2c methodsFor: 'GUI building' stamp: 'hjh 1/16/2013 11:18'!
buildMorphicWindow


     	self setLabel: self className.
	
	self beRow.

	self layoutMorph  addMorphUseAll: 
	   (RectangleLikeMorph new color: Color red).

	self layoutMorph  addMorphUseAll: 
	   (RectangleLikeMorph new color: Color yellow).
	
 	self layoutMorph  addMorphUseAll: 
	   (RectangleLikeMorph new color: Color green) 
 
	! !

!LayoutDemo2c methodsFor: 'initialization' stamp: 'hjh 1/16/2013 06:20'!
initialize

	super initialize.
	
	self buildMorphicWindow.! !

!LayoutDemo2d methodsFor: 'GUI building' stamp: 'hjh 1/16/2013 10:26'!
buildMorphicWindow


     	self setLabel: self className.

	self layoutMorph  
	 addMorph: 
	    ((UpdatingStringMorph new
      			target: ['Cursor position: ',
				            self runningWorld activeHand morphPosition asString
				           ];
		            getSelector: #value;
     			      stepTime: 10) color: Color blue) 
	 fixedHeight: 80.
	
 	self layoutMorph  addMorphUseAll: 
	   (UpdatingStringMorph new
      			target: ['self morphBoundsInWorld ',
				            self morphBoundsInWorld asString];
		            getSelector: #value;
     			      stepTime: 10) 
 
	! !

!LayoutDemo2d methodsFor: 'initialization' stamp: 'hjh 1/16/2013 09:51'!
initialize

	super initialize.
	
	self buildMorphicWindow.
	
	self inspect! !

!LayoutDemo2e methodsFor: 'GUI building' stamp: 'hjh 1/16/2013 11:11'!
buildMorphicWindow


     	self setLabel: self className.

	self layoutMorph  
	 addMorph: 
	    ((UpdatingStringMorph new
      			target: ['Cursor position: ',
				            self runningWorld activeHand morphPosition asString
				           ];
		            getSelector: #value;
     			      stepTime: 10) color: Color blue) 
	 fixedHeight: 80.
	
 	self layoutMorph  addMorphUseAll: 
	   (UpdatingStringMorph new
      			target: ['self morphBoundsInWorld ',
				            self morphBoundsInWorld asString];
		            getSelector: #value;
     			      stepTime: 10). 
 
 	self layoutMorph  addMorph: 
	   (UpdatingStringMorph new
      			target: [Date today asString];
		            getSelector: #value;
     			      stepTime: 10) 
	 fixedHeight: 30.
	! !

!LayoutDemo2e methodsFor: 'initialization' stamp: 'hjh 1/16/2013 11:11'!
initialize

	super initialize.
	
	self buildMorphicWindow.
	! !

!LayoutDemo3 methodsFor: 'GUI building' stamp: 'hjh 1/16/2013 12:41'!
buildMorphicWindow

self setLabel: self className.

contentArea := RectangleLikeMorph new color: Color green.


self layoutMorph addMorph:  self createButtonBar fixedHeight: 60.
self layoutMorph addMorphUseAll: contentArea.

self openInWorld

! !

!LayoutDemo3 methodsFor: 'GUI building' stamp: 'hjh 1/16/2013 10:48'!
createButtonBar

^ LayoutMorph newRow 
    addMorph: 
        (PluggableButtonMorph 
			model: [ contentArea color: Color red] action: #value label: 'red'
	  ) 
    fixedWidth: 70;
	
    addMorph: 
      (PluggableButtonMorph 
			model: [ contentArea color: Color green] action: #value label: 'green'
	) 
    fixedWidth: 70;
	
    addMorph: 
       (PluggableButtonMorph 
			model: [ contentArea color: Color blue] action: #value label: 'blue'
	 ) 
	 fixedWidth: 70;
      
    addMorph: 
       (PluggableButtonMorph 
			model: [ contentArea color: Color yellow] action: #value label: 'yellow'
	 ) 
	fixedWidth: 70
	! !

!LayoutDemo3 methodsFor: 'initialization' stamp: 'hjh 1/12/2013 11:18'!
initialize

	super initialize.
	self buildMorphicWindow.! !

!LayoutDemo3 methodsFor: 'GUI building' stamp: 'hjh 1/12/2013 11:21'!
initializeLabelArea
	"Initialize the label area (titlebar) for the window.
	This is a shorter version of inherited #initializeLabelArea.
	We do not create the other controls"

	|  box |

	box _ self createCloseBox.
	self addMorph: box.
	box morphPosition: 2@2.
	box morphExtent: self boxExtent.

! !

!LayoutDemo4 methodsFor: 'GUI building' stamp: 'hjh 1/16/2013 12:51'!
buildMorphicWindow

self setLabel: self className.


self layoutMorph addMorph:  self createButtonBar fixedHeight: 60.
self layoutMorph addMorphUseAll: self makePages.

self openInWorld
! !

!LayoutDemo4 methodsFor: 'GUI building' stamp: 'hjh 1/12/2013 11:51'!
createButtonBar


^ LayoutMorph newRow 
	
addMorph: (PluggableButtonMorph 
			model: [ contentArea color: Color red] action: #value label: 'red') 
	            fixedWidth: 70;
	
addMorph: (PluggableButtonMorph 
			model: [ contentArea color: Color green] action: #value label: 'green') 
	           fixedWidth: 70;
	
addMorph: (PluggableButtonMorph 
			model: [ contentArea color: Color blue] action: #value label: 'blue') 
	           fixedWidth: 70;

addMorph: (PluggableButtonMorph 
			model: [ contentArea color: Color yellow] action: #value label: 'yellow') 
	           fixedWidth: 70! !

!LayoutDemo4 methodsFor: 'initialization' stamp: 'hjh 1/12/2013 11:18'!
initialize

	super initialize.
	self buildMorphicWindow.! !

!LayoutDemo4 methodsFor: 'GUI building' stamp: 'hjh 1/12/2013 11:21'!
initializeLabelArea
	"Initialize the label area (titlebar) for the window.
	This is a shorter version of inherited #initializeLabelArea.
	We do not create the other controls"

	|  box |

	box _ self createCloseBox.
	self addMorph: box.
	box morphPosition: 2@2.
	box morphExtent: self boxExtent.

! !

!LayoutDemo4 methodsFor: 'page creation' stamp: 'hjh 1/16/2013 12:58'!
makePages


      ^contentArea := RectangleLikeMorph new color: Color green.! !

!LayoutDemo4b methodsFor: 'GUI building' stamp: 'hjh 1/16/2013 12:51'!
buildMorphicWindow

self setLabel: self className.


self layoutMorph addMorph:  self createButtonBar fixedHeight: 60.
self layoutMorph addMorphUseAll: self makePages.

self openInWorld
! !

!LayoutDemo4b methodsFor: 'GUI building' stamp: 'hjh 1/12/2013 11:51'!
createButtonBar


^ LayoutMorph newRow 
	
addMorph: (PluggableButtonMorph 
			model: [ contentArea color: Color red] action: #value label: 'red') 
	            fixedWidth: 70;
	
addMorph: (PluggableButtonMorph 
			model: [ contentArea color: Color green] action: #value label: 'green') 
	           fixedWidth: 70;
	
addMorph: (PluggableButtonMorph 
			model: [ contentArea color: Color blue] action: #value label: 'blue') 
	           fixedWidth: 70;

addMorph: (PluggableButtonMorph 
			model: [ contentArea color: Color yellow] action: #value label: 'yellow') 
	           fixedWidth: 70! !

!LayoutDemo4b methodsFor: 'initialization' stamp: 'hjh 1/12/2013 11:18'!
initialize

	super initialize.
	self buildMorphicWindow.! !

!LayoutDemo4b methodsFor: 'GUI building' stamp: 'hjh 1/12/2013 11:21'!
initializeLabelArea
	"Initialize the label area (titlebar) for the window.
	This is a shorter version of inherited #initializeLabelArea.
	We do not create the other controls"

	|  box |

	box _ self createCloseBox.
	self addMorph: box.
	box morphPosition: 2@2.
	box morphExtent: self boxExtent.

! !

!LayoutDemo4b methodsFor: 'page creation' stamp: 'hjh 1/16/2013 13:06'!
makePages

 	contentArea := RectangleLikeMorph new color: Color gray.
	

      contentArea addMorph: ((RectangleLikeMorph new color: Color red) morphExtent: 320@240).
	contentArea addMorph: ((RectangleLikeMorph new color: Color green)  morphExtent: 310@230).
	contentArea addMorph: ((RectangleLikeMorph new color: Color blue)  morphExtent: 305@225).
	contentArea addMorph: ((RectangleLikeMorph new color: Color yellow)  morphExtent: 300@220).
	
	^ contentArea


    ! !

!LayoutDemo5 methodsFor: 'GUI building' stamp: 'hjh 1/16/2013 12:40'!
buildMorphicWindow


  self layoutMorph addMorph: self createButtonBar fixedHeight: 40.  self layoutMorph addMorphUseAll: self makePages.
  self setLabel: self className.
  self openInWorld.

  currentPage := 1.

  self displayPage: currentPage.
! !

!LayoutDemo5 methodsFor: 'GUI building' stamp: 'hjh 1/12/2013 12:37'!
createButtonBar


^ LayoutMorph newRow 
	
addMorph: (PluggableButtonMorph 
			model: [ self showPage: 1] action: #value label: 'red') 
	            fixedWidth: 70;
	
addMorph: (PluggableButtonMorph 
			model: [ self showPage: 2] action: #value label: 'green') 
	           fixedWidth: 70;
	
addMorph: (PluggableButtonMorph 
			model: [ self showPage: 3] action: #value label: 'blue') 
	           fixedWidth: 70;

addMorph: (PluggableButtonMorph 
			model: [ self showPage: 4] action: #value label: 'yellow') 
	           fixedWidth: 70! !

!LayoutDemo5 methodsFor: 'page display' stamp: 'hjh 1/12/2013 12:18'!
displayPage: pageNumber
	| page |
	"self adjustButtonsForPage: pageNumber."
	page := pages at: pageNumber.
	page show! !

!LayoutDemo5 methodsFor: 'page display' stamp: 'hjh 1/12/2013 12:35'!
hideCurrentPage
	| page |
	page := pages at: currentPage.
	page hide! !

!LayoutDemo5 methodsFor: 'initialization' stamp: 'hjh 1/12/2013 11:18'!
initialize

	super initialize.
	self buildMorphicWindow.! !

!LayoutDemo5 methodsFor: 'GUI building' stamp: 'hjh 1/12/2013 11:21'!
initializeLabelArea
	"Initialize the label area (titlebar) for the window.
	This is a shorter version of inherited #initializeLabelArea.
	We do not create the other controls"

	|  box |

	box _ self createCloseBox.
	self addMorph: box.
	box morphPosition: 2@2.
	box morphExtent: self boxExtent.

! !

!LayoutDemo5 methodsFor: 'page creation' stamp: 'hjh 1/16/2013 14:04'!
makePages
	| contentArea |
	pages := OrderedCollection new.
	pages add: ((RectangleLikeMorph new color: Color red) morphExtent: 320@240).
	pages add: ((RectangleLikeMorph new color: Color green)  morphExtent: 310@230).
	pages add: ((RectangleLikeMorph new color: Color blue)  morphExtent: 305@225).
	pages add: ((RectangleLikeMorph new color: Color yellow)  morphExtent: 300@220).
	

	contentArea _ RectangleLikeMorph  new color: Color white.
	
	pages do: [:each | contentArea addMorph: each. 
						each hide].
	
	^contentArea
	! !

!LayoutDemo5 methodsFor: 'page display' stamp: 'hjh 1/12/2013 12:36'!
nextPage
	self hideCurrentPage.
	currentPage := currentPage + 1.
	self displayPage: currentPage! !

!LayoutDemo5 methodsFor: 'page display' stamp: 'hjh 1/12/2013 12:36'!
showPage: aNumber.
	self hideCurrentPage.
	currentPage := aNumber.
	self displayPage: currentPage! !

!LayoutDemo5 methodsFor: 'initialization' stamp: 'hjh 1/12/2013 11:57'!
titleString

	^self class name ! !

!LayoutDemo6 methodsFor: 'GUI building' stamp: 'hjh 1/16/2013 14:12'!
buildMorphicWindow


  self layoutMorph addMorph: self createButtonBar fixedHeight: 40.
  self layoutMorph addMorphUseAll: (contentArea := self makePages).
  self setLabel: self className.
  self openInWorld.

  currentPage := 1.

  self displayPage: currentPage.! !

!LayoutDemo6 methodsFor: 'GUI building' stamp: 'hjh 1/12/2013 12:37'!
createButtonBar


^ LayoutMorph newRow 
	
addMorph: (PluggableButtonMorph 
			model: [ self showPage: 1] action: #value label: 'red') 
	            fixedWidth: 70;
	
addMorph: (PluggableButtonMorph 
			model: [ self showPage: 2] action: #value label: 'green') 
	           fixedWidth: 70;
	
addMorph: (PluggableButtonMorph 
			model: [ self showPage: 3] action: #value label: 'blue') 
	           fixedWidth: 70;

addMorph: (PluggableButtonMorph 
			model: [ self showPage: 4] action: #value label: 'yellow') 
	           fixedWidth: 70! !

!LayoutDemo6 methodsFor: 'page display' stamp: 'hjh 1/16/2013 14:13'!
displayPage: pageNumber
	| page |
	"self adjustButtonsForPage: pageNumber."
	page := pages at: pageNumber.
	contentArea addMorphUseAll: page.
	contentArea layoutSubmorphs! !

!LayoutDemo6 methodsFor: 'page display' stamp: 'hjh 1/16/2013 14:14'!
hideCurrentPage
	| page |
	page := pages at: currentPage.
      contentArea removeMorph: page.
! !

!LayoutDemo6 methodsFor: 'initialization' stamp: 'hjh 1/12/2013 18:21'!
initialize

	super initialize.
	
	self buildMorphicWindow.! !

!LayoutDemo6 methodsFor: 'GUI building' stamp: 'hjh 1/12/2013 11:21'!
initializeLabelArea
	"Initialize the label area (titlebar) for the window.
	This is a shorter version of inherited #initializeLabelArea.
	We do not create the other controls"

	|  box |

	box _ self createCloseBox.
	self addMorph: box.
	box morphPosition: 2@2.
	box morphExtent: self boxExtent.

! !

!LayoutDemo6 methodsFor: 'page creation' stamp: 'hjh 1/16/2013 14:15'!
makePages
	| r |
	pages := OrderedCollection new.
	
	pages add: (RectangleLikeMorph new color: Color red; morphWidth: 400; morphHeight: 300).
	pages add: (RectangleLikeMorph new color: Color green; morphWidth: 400; morphHeight: 300).
	pages add: (RectangleLikeMorph new color: Color blue; morphWidth: 400; morphHeight: 300).
	pages add: (RectangleLikeMorph new color: Color yellow; morphWidth: 400; morphHeight: 300).
	
	
	r _ LayoutMorph  newRow color: Color gray; morphWidth: 180; morphHeight: 100.
	r addMorph: (pages at: 1).
	
	^r
	! !

!LayoutDemo6 methodsFor: 'page display' stamp: 'hjh 1/12/2013 12:36'!
nextPage
	self hideCurrentPage.
	currentPage := currentPage + 1.
	self displayPage: currentPage! !

!LayoutDemo6 methodsFor: 'page display' stamp: 'hjh 1/12/2013 12:36'!
showPage: aNumber.
	self hideCurrentPage.
	currentPage := aNumber.
	self displayPage: currentPage! !

!LayoutDemo6 methodsFor: 'initialization' stamp: 'hjh 1/12/2013 11:57'!
titleString

	^self class name ! !

!LayoutDemo6b methodsFor: 'GUI building' stamp: 'hjh 1/16/2013 14:12'!
buildMorphicWindow


  self layoutMorph addMorph: self createButtonBar fixedHeight: 40.
  self layoutMorph addMorphUseAll: (contentArea := self makePages).
  self setLabel: self className.
  self openInWorld.

  currentPage := 1.

  self displayPage: currentPage.! !

!LayoutDemo6b methodsFor: 'GUI building' stamp: 'hjh 1/12/2013 12:37'!
createButtonBar


^ LayoutMorph newRow 
	
addMorph: (PluggableButtonMorph 
			model: [ self showPage: 1] action: #value label: 'red') 
	            fixedWidth: 70;
	
addMorph: (PluggableButtonMorph 
			model: [ self showPage: 2] action: #value label: 'green') 
	           fixedWidth: 70;
	
addMorph: (PluggableButtonMorph 
			model: [ self showPage: 3] action: #value label: 'blue') 
	           fixedWidth: 70;

addMorph: (PluggableButtonMorph 
			model: [ self showPage: 4] action: #value label: 'yellow') 
	           fixedWidth: 70! !

!LayoutDemo6b methodsFor: 'page display' stamp: 'hjh 1/16/2013 14:13'!
displayPage: pageNumber
	| page |
	"self adjustButtonsForPage: pageNumber."
	page := pages at: pageNumber.
	contentArea addMorphUseAll: page.
	contentArea layoutSubmorphs! !

!LayoutDemo6b methodsFor: 'page display' stamp: 'hjh 1/16/2013 14:14'!
hideCurrentPage
	| page |
	page := pages at: currentPage.
      contentArea removeMorph: page.
! !

!LayoutDemo6b methodsFor: 'initialization' stamp: 'hjh 1/16/2013 14:24'!
initialize
	super initialize.

	self buildMorphicWindow.! !

!LayoutDemo6b methodsFor: 'GUI building' stamp: 'hjh 1/12/2013 11:21'!
initializeLabelArea
	"Initialize the label area (titlebar) for the window.
	This is a shorter version of inherited #initializeLabelArea.
	We do not create the other controls"

	|  box |

	box _ self createCloseBox.
	self addMorph: box.
	box morphPosition: 2@2.
	box morphExtent: self boxExtent.

! !

!LayoutDemo6b methodsFor: 'page creation' stamp: 'hjh 1/16/2013 14:27'!
makePages
	| r page1 page2 page3 |
	pages := OrderedCollection new.
	
	pages add: (page1 _ RectangleLikeMorph new color: Color red).
	pages add: (page2 _ RectangleLikeMorph new color: Color green).
	pages add: (page3 _ RectangleLikeMorph new color: Color blue).
	pages add: (RectangleLikeMorph new color: Color yellow).
	
	page1 addMorph: (EllipseMorph new morphPosition: 40@60; morphWidth: 100; morphHeight:100;
						color: Color white).
      page2 addMorph: ((LimitedHeightTextMorph new
						maxHeight: 48;
						model: (TextModel new contents: 'abc def ghi jkl mno pqr stu vwx yz'))
						morphPosition: 40@60).
								
	page3 addMorph: (EllipseMorph new morphPosition: 89@20; morphWidth: 50; morphHeight:50).
.

	
	r _ LayoutMorph  newRow color: Color gray; morphWidth: 180; morphHeight: 100.
	r addMorphUseAll: (pages at: 1).
	
	^r
	! !

!LayoutDemo6b methodsFor: 'page display' stamp: 'hjh 1/12/2013 12:36'!
nextPage
	self hideCurrentPage.
	currentPage := currentPage + 1.
	self displayPage: currentPage! !

!LayoutDemo6b methodsFor: 'page display' stamp: 'hjh 1/12/2013 12:36'!
showPage: aNumber.
	self hideCurrentPage.
	currentPage := aNumber.
	self displayPage: currentPage! !

!LayoutDemo6b methodsFor: 'initialization' stamp: 'hjh 1/12/2013 11:57'!
titleString

	^self class name ! !

!LayoutDemo6c methodsFor: 'GUI building' stamp: 'hjh 1/16/2013 14:12'!
buildMorphicWindow


  self layoutMorph addMorph: self createButtonBar fixedHeight: 40.
  self layoutMorph addMorphUseAll: (contentArea := self makePages).
  self setLabel: self className.
  self openInWorld.

  currentPage := 1.

  self displayPage: currentPage.! !

!LayoutDemo6c methodsFor: 'GUI building' stamp: 'hjh 1/12/2013 12:37'!
createButtonBar


^ LayoutMorph newRow 
	
addMorph: (PluggableButtonMorph 
			model: [ self showPage: 1] action: #value label: 'red') 
	            fixedWidth: 70;
	
addMorph: (PluggableButtonMorph 
			model: [ self showPage: 2] action: #value label: 'green') 
	           fixedWidth: 70;
	
addMorph: (PluggableButtonMorph 
			model: [ self showPage: 3] action: #value label: 'blue') 
	           fixedWidth: 70;

addMorph: (PluggableButtonMorph 
			model: [ self showPage: 4] action: #value label: 'yellow') 
	           fixedWidth: 70! !

!LayoutDemo6c methodsFor: 'page creation' stamp: 'hjh 1/16/2013 15:11'!
createPage1


| page1 |

								

page1 _ RectangleLikeMorph new color: Color red.

page1 addMorph: (EllipseMorph new morphPosition: 40@60; morphWidth: 100; morphHeight:100;
						color: Color white).
     
^page1! !

!LayoutDemo6c methodsFor: 'page creation' stamp: 'hjh 1/16/2013 15:09'!
createPage2


| page2 |

								

page2 _ RectangleLikeMorph new color: Color green.

page2 addMorph: ((LimitedHeightTextMorph new
						maxHeight: 48;
						model: (TextModel new contents: 'abc def ghi jkl mno pqr stu vwx yz'))
						morphPosition: 40@60).

^page2! !

!LayoutDemo6c methodsFor: 'page creation' stamp: 'hjh 1/16/2013 15:08'!
createPage3


| page3 |

page3 _ RectangleLikeMorph new color: Color blue.

page3 addMorph: (EllipseMorph new morphPosition: 89@20; morphWidth: 50; morphHeight:50).

^page3! !

!LayoutDemo6c methodsFor: 'page display' stamp: 'hjh 1/16/2013 14:13'!
displayPage: pageNumber
	| page |
	"self adjustButtonsForPage: pageNumber."
	page := pages at: pageNumber.
	contentArea addMorphUseAll: page.
	contentArea layoutSubmorphs! !

!LayoutDemo6c methodsFor: 'page display' stamp: 'hjh 1/16/2013 14:14'!
hideCurrentPage
	| page |
	page := pages at: currentPage.
      contentArea removeMorph: page.
! !

!LayoutDemo6c methodsFor: 'initialization' stamp: 'hjh 1/16/2013 14:24'!
initialize
	super initialize.

	self buildMorphicWindow.! !

!LayoutDemo6c methodsFor: 'GUI building' stamp: 'hjh 1/12/2013 11:21'!
initializeLabelArea
	"Initialize the label area (titlebar) for the window.
	This is a shorter version of inherited #initializeLabelArea.
	We do not create the other controls"

	|  box |

	box _ self createCloseBox.
	self addMorph: box.
	box morphPosition: 2@2.
	box morphExtent: self boxExtent.

! !

!LayoutDemo6c methodsFor: 'page creation' stamp: 'hjh 1/16/2013 15:12'!
makePages
	| p  |
	pages := OrderedCollection new.
	
	pages add: self createPage1.
	pages add: self createPage2.
	pages add: self createPage3.
	pages add: (RectangleLikeMorph new color: Color yellow).
	
	
	p _ LayoutMorph  newRow color: Color gray; morphWidth: 180; morphHeight: 100.
	p addMorphUseAll: (pages at: 1).
	
	^p
	! !

!LayoutDemo6c methodsFor: 'page display' stamp: 'hjh 1/12/2013 12:36'!
nextPage
	self hideCurrentPage.
	currentPage := currentPage + 1.
	self displayPage: currentPage! !

!LayoutDemo6c methodsFor: 'page display' stamp: 'hjh 1/12/2013 12:36'!
showPage: aNumber.
	self hideCurrentPage.
	currentPage := aNumber.
	self displayPage: currentPage! !

!LayoutDemo6c methodsFor: 'initialization' stamp: 'hjh 1/12/2013 11:57'!
titleString

	^self class name ! !

!LayoutDemo6d methodsFor: 'GUI building' stamp: 'hjh 1/16/2013 14:12'!
buildMorphicWindow


  self layoutMorph addMorph: self createButtonBar fixedHeight: 40.
  self layoutMorph addMorphUseAll: (contentArea := self makePages).
  self setLabel: self className.
  self openInWorld.

  currentPage := 1.

  self displayPage: currentPage.! !

!LayoutDemo6d methodsFor: 'GUI building' stamp: 'hjh 1/12/2013 12:37'!
createButtonBar


^ LayoutMorph newRow 
	
addMorph: (PluggableButtonMorph 
			model: [ self showPage: 1] action: #value label: 'red') 
	            fixedWidth: 70;
	
addMorph: (PluggableButtonMorph 
			model: [ self showPage: 2] action: #value label: 'green') 
	           fixedWidth: 70;
	
addMorph: (PluggableButtonMorph 
			model: [ self showPage: 3] action: #value label: 'blue') 
	           fixedWidth: 70;

addMorph: (PluggableButtonMorph 
			model: [ self showPage: 4] action: #value label: 'yellow') 
	           fixedWidth: 70! !

!LayoutDemo6d methodsFor: 'page creation' stamp: 'hjh 1/29/2013 16:16'!
createPage1


| page1 |

								

page1 _ DragAndDropAreaMorph new color: Color red.

page1 addMorph: (EllipseMorph new morphPosition: 40@60; morphWidth: 100; morphHeight:100;
						color: Color white).
     
^page1! !

!LayoutDemo6d methodsFor: 'page creation' stamp: 'hjh 1/29/2013 16:16'!
createPage2


| page2 |

								

page2 _ DragAndDropAreaMorph new color: Color green.

page2 addMorph: ((LimitedHeightTextMorph new
						maxHeight: 48;
						model: (TextModel new contents: 'abc def ghi jkl mno pqr stu vwx yz'))
						morphPosition: 40@60).

^page2! !

!LayoutDemo6d methodsFor: 'page creation' stamp: 'hjh 1/16/2013 15:36'!
createPage3

| page3 col |

page3 _ LayoutMorph newRow color: Color gray; morphWidth: 400; morphHeight:300.

10 timesRepeat: [

    col _ LayoutMorph  newColumn color: Color blue.

    col addMorphUseAll: (EllipseMorph new morphWidth: 50; morphHeight:60).
    col addMorphUseAll: (EllipseMorph new color: Color random; morphWidth: 50; morphHeight:60).
    col addMorphUseAll: (EllipseMorph new color: Color tan; morphWidth: 50; morphHeight:60).
    col addMorphUseAll: (EllipseMorph new color: Color random; morphWidth: 50; morphHeight:60).
    col addMorphUseAll: (EllipseMorph new color: Color brown; morphWidth: 50; morphHeight:60).
   
 page3 addMorphUseAll: col.
].

^page3! !

!LayoutDemo6d methodsFor: 'page display' stamp: 'hjh 1/16/2013 14:13'!
displayPage: pageNumber
	| page |
	"self adjustButtonsForPage: pageNumber."
	page := pages at: pageNumber.
	contentArea addMorphUseAll: page.
	contentArea layoutSubmorphs! !

!LayoutDemo6d methodsFor: 'page display' stamp: 'hjh 1/16/2013 14:14'!
hideCurrentPage
	| page |
	page := pages at: currentPage.
      contentArea removeMorph: page.
! !

!LayoutDemo6d methodsFor: 'initialization' stamp: 'hjh 1/16/2013 14:24'!
initialize
	super initialize.

	self buildMorphicWindow.! !

!LayoutDemo6d methodsFor: 'GUI building' stamp: 'hjh 1/12/2013 11:21'!
initializeLabelArea
	"Initialize the label area (titlebar) for the window.
	This is a shorter version of inherited #initializeLabelArea.
	We do not create the other controls"

	|  box |

	box _ self createCloseBox.
	self addMorph: box.
	box morphPosition: 2@2.
	box morphExtent: self boxExtent.

! !

!LayoutDemo6d methodsFor: 'page creation' stamp: 'hjh 1/29/2013 16:16'!
makePages
	| p  |
	pages := OrderedCollection new.
	
	pages add: self createPage1.
	pages add: self createPage2.
	pages add: self createPage3.
	pages add: (DragAndDropAreaMorph new color: Color yellow).
	
	
	p _ LayoutMorph  newRow color: Color gray; morphWidth: 180; morphHeight: 100.
	p addMorphUseAll: (pages at: 1).
	
	^p
	! !

!LayoutDemo6d methodsFor: 'page display' stamp: 'hjh 1/12/2013 12:36'!
nextPage
	self hideCurrentPage.
	currentPage := currentPage + 1.
	self displayPage: currentPage! !

!LayoutDemo6d methodsFor: 'page display' stamp: 'hjh 1/12/2013 12:36'!
showPage: aNumber.
	self hideCurrentPage.
	currentPage := aNumber.
	self displayPage: currentPage! !

!LayoutDemo6d methodsFor: 'initialization' stamp: 'hjh 1/12/2013 11:57'!
titleString

	^self class name ! !

!LayoutDemo7 methodsFor: 'GUI building' stamp: 'hjh 1/29/2013 18:10'!
buildMorphicWindow


  self layoutMorph addMorph: self createButtonBar fixedHeight: 40.
  self layoutMorph addMorphUseAll: (contentArea := self makePages).
  self setLabel: self titleString.
  self openInWorld.

  currentPage := 1.

  self displayPage: currentPage.! !

!LayoutDemo7 methodsFor: 'GUI building' stamp: 'hjh 1/12/2013 12:37'!
createButtonBar


^ LayoutMorph newRow 
	
addMorph: (PluggableButtonMorph 
			model: [ self showPage: 1] action: #value label: 'red') 
	            fixedWidth: 70;
	
addMorph: (PluggableButtonMorph 
			model: [ self showPage: 2] action: #value label: 'green') 
	           fixedWidth: 70;
	
addMorph: (PluggableButtonMorph 
			model: [ self showPage: 3] action: #value label: 'blue') 
	           fixedWidth: 70;

addMorph: (PluggableButtonMorph 
			model: [ self showPage: 4] action: #value label: 'yellow') 
	           fixedWidth: 70! !

!LayoutDemo7 methodsFor: 'page creation' stamp: 'hjh 1/29/2013 16:16'!
createPage1


| page1 |

								

page1 _ DragAndDropAreaMorph new color: Color red.

page1 addMorph: (EllipseMorph new morphPosition: 40@60; morphWidth: 100; morphHeight:100;
						color: Color white).
     
^page1! !

!LayoutDemo7 methodsFor: 'page creation' stamp: 'hjh 1/29/2013 16:16'!
createPage2


| page2 |

								

page2 _ DragAndDropAreaMorph new color: Color green.

page2 addMorph: ((LimitedHeightTextMorph new
						maxHeight: 48;
						model: (TextModel new contents: 'abc def ghi jkl mno pqr stu vwx yz'))
						morphPosition: 40@60).

^page2! !

!LayoutDemo7 methodsFor: 'page creation' stamp: 'hjh 1/29/2013 17:00'!
createPage3

| page3 |

page3 _ LayoutMorph newRow color: Color gray; morphWidth: 400; morphHeight:300.

25 timesRepeat: [page3 addMorphUseAll: (RectangleLikeMorph new color: Color red lighter)].
5 timesRepeat: [page3 addMorphUseAll: (RectangleLikeMorph new color: Color random)].





^page3! !

!LayoutDemo7 methodsFor: 'page display' stamp: 'hjh 1/16/2013 14:13'!
displayPage: pageNumber
	| page |
	"self adjustButtonsForPage: pageNumber."
	page := pages at: pageNumber.
	contentArea addMorphUseAll: page.
	contentArea layoutSubmorphs! !

!LayoutDemo7 methodsFor: 'page display' stamp: 'hjh 1/16/2013 14:14'!
hideCurrentPage
	| page |
	page := pages at: currentPage.
      contentArea removeMorph: page.
! !

!LayoutDemo7 methodsFor: 'initialization' stamp: 'hjh 1/16/2013 14:24'!
initialize
	super initialize.

	self buildMorphicWindow.! !

!LayoutDemo7 methodsFor: 'GUI building' stamp: 'hjh 1/12/2013 11:21'!
initializeLabelArea
	"Initialize the label area (titlebar) for the window.
	This is a shorter version of inherited #initializeLabelArea.
	We do not create the other controls"

	|  box |

	box _ self createCloseBox.
	self addMorph: box.
	box morphPosition: 2@2.
	box morphExtent: self boxExtent.

! !

!LayoutDemo7 methodsFor: 'page creation' stamp: 'hjh 1/29/2013 16:16'!
makePages
	| p  |
	pages := OrderedCollection new.
	
	pages add: self createPage1.
	pages add: self createPage2.
	pages add: self createPage3.
	pages add: (DragAndDropAreaMorph new color: Color yellow).
	
	
	p _ LayoutMorph  newRow color: Color gray; morphWidth: 180; morphHeight: 100.
	p addMorphUseAll: (pages at: 1).
	
	^p
	! !

!LayoutDemo7 methodsFor: 'page display' stamp: 'hjh 1/12/2013 12:36'!
nextPage
	self hideCurrentPage.
	currentPage := currentPage + 1.
	self displayPage: currentPage! !

!LayoutDemo7 methodsFor: 'page display' stamp: 'hjh 1/12/2013 12:36'!
showPage: aNumber.
	self hideCurrentPage.
	currentPage := aNumber.
	self displayPage: currentPage! !

!LayoutDemo7 methodsFor: 'initialization' stamp: 'hjh 1/12/2013 11:57'!
titleString

	^self class name ! !

!LayoutDemo8Timer methodsFor: 'GUI building' stamp: 'hjh 1/29/2013 19:02'!
buildMorphicWindow


 
  self setLabel: self titleString.
  self layoutMorph beRow.
  25 timesRepeat: [ | circle | circle := (EllipseMorph new color: Color red muchLighter; 
	morphExtent: 20@20).
	minuteMorphs add: circle.
	self layoutMorph addMorph: circle].

  5 timesRepeat: [ | circle | circle := (EllipseMorph new color: Color blue muchLighter; 
	morphExtent: 20@20).
	minuteMorphs add: circle.
	self layoutMorph addMorph: circle].

 ! !

!LayoutDemo8Timer methodsFor: 'GUI building' stamp: 'hjh 1/29/2013 21:53'!
initialExtent
	
	
	^ 610 @ 40! !

!LayoutDemo8Timer methodsFor: 'initialization' stamp: 'hjh 1/29/2013 21:30'!
initialize
	super initialize.
	
	minuteMorphs := OrderedCollection new.
	startTime := Time now.

	self buildMorphicWindow.! !

!LayoutDemo8Timer methodsFor: 'GUI building' stamp: 'hjh 1/29/2013 18:12'!
initializeLabelArea
	"Initialize the label area (titlebar) for the window.
	This is a shorter version of inherited #initializeLabelArea.
	We do not create the other controls"

	|  box |

	box _ self createCloseBox.
	self addMorph: box.
	box morphPosition: 2@2.
	box morphExtent: self boxExtent.

! !

!LayoutDemo8Timer methodsFor: 'updating' stamp: 'hjh 1/29/2013 21:49'!
step
	| currentColor currentMorph minutes |

	
	minutes := (Time now - startTime) minutes.
	minutes > 0 ifTrue: [
				currentMorph := minuteMorphs at:  minutes ifAbsent: [minuteMorphs last].
			
				currentColor := currentMorph color darker.
				minutes <= 25 ifTrue: [currentColor := Color red]. "set to red for the first 25"
				currentMorph color: currentColor
				]! !

!LayoutDemo8Timer methodsFor: 'updating' stamp: 'hjh 1/29/2013 21:50'!
stepTime

	^5000! !

!LayoutDemo8Timer methodsFor: 'initialization' stamp: 'hjh 1/29/2013 18:08'!
titleString

	^'Timer'! !

!LayoutDemo8Timer methodsFor: 'updating' stamp: 'hjh 1/29/2013 18:47'!
wantsSteps
	"Return true if the receiver wants to its #step or #stepAt: methods be run"

	^true! !
