'From Cuis 4.1 of 12 December 2012 [latest update: #1590] on 11 February 2013 at 10:33:26 pm'!
'Description Add-Ons which show how Morphic works'!
!classDefinition: #LayoutDemo0 category: #'Add-Ons-LayoutDemo'!
SystemWindow subclass: #LayoutDemo0
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Add-Ons-LayoutDemo'!
!classDefinition: 'LayoutDemo0 class' category: #'Add-Ons-LayoutDemo'!
LayoutDemo0 class
	instanceVariableNames: ''!

!classDefinition: #LayoutDemo1 category: #'Add-Ons-LayoutDemo'!
SystemWindow subclass: #LayoutDemo1
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Add-Ons-LayoutDemo'!
!classDefinition: 'LayoutDemo1 class' category: #'Add-Ons-LayoutDemo'!
LayoutDemo1 class
	instanceVariableNames: ''!

!classDefinition: #LayoutDemo1b category: #'Add-Ons-LayoutDemo'!
SystemWindow subclass: #LayoutDemo1b
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Add-Ons-LayoutDemo'!
!classDefinition: 'LayoutDemo1b class' category: #'Add-Ons-LayoutDemo'!
LayoutDemo1b class
	instanceVariableNames: ''!

!classDefinition: #LayoutDemo2 category: #'Add-Ons-LayoutDemo'!
SystemWindow subclass: #LayoutDemo2
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Add-Ons-LayoutDemo'!
!classDefinition: 'LayoutDemo2 class' category: #'Add-Ons-LayoutDemo'!
LayoutDemo2 class
	instanceVariableNames: ''!

!classDefinition: #LayoutDemo2b category: #'Add-Ons-LayoutDemo'!
SystemWindow subclass: #LayoutDemo2b
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Add-Ons-LayoutDemo'!
!classDefinition: 'LayoutDemo2b class' category: #'Add-Ons-LayoutDemo'!
LayoutDemo2b class
	instanceVariableNames: ''!

!classDefinition: #LayoutDemo2c category: #'Add-Ons-LayoutDemo'!
SystemWindow subclass: #LayoutDemo2c
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Add-Ons-LayoutDemo'!
!classDefinition: 'LayoutDemo2c class' category: #'Add-Ons-LayoutDemo'!
LayoutDemo2c class
	instanceVariableNames: ''!

!classDefinition: #LayoutDemo2d category: #'Add-Ons-LayoutDemo'!
SystemWindow subclass: #LayoutDemo2d
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Add-Ons-LayoutDemo'!
!classDefinition: 'LayoutDemo2d class' category: #'Add-Ons-LayoutDemo'!
LayoutDemo2d class
	instanceVariableNames: ''!

!classDefinition: #LayoutDemo2e category: #'Add-Ons-LayoutDemo'!
SystemWindow subclass: #LayoutDemo2e
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Add-Ons-LayoutDemo'!
!classDefinition: 'LayoutDemo2e class' category: #'Add-Ons-LayoutDemo'!
LayoutDemo2e class
	instanceVariableNames: ''!

!classDefinition: #LayoutDemo3 category: #'Add-Ons-LayoutDemo'!
SystemWindow subclass: #LayoutDemo3
	instanceVariableNames: 'contentArea'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Add-Ons-LayoutDemo'!
!classDefinition: 'LayoutDemo3 class' category: #'Add-Ons-LayoutDemo'!
LayoutDemo3 class
	instanceVariableNames: ''!

!classDefinition: #LayoutDemo3b category: #'Add-Ons-LayoutDemo'!
SystemWindow subclass: #LayoutDemo3b
	instanceVariableNames: 'contentArea'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Add-Ons-LayoutDemo'!
!classDefinition: 'LayoutDemo3b class' category: #'Add-Ons-LayoutDemo'!
LayoutDemo3b class
	instanceVariableNames: ''!

!classDefinition: #LayoutDemo3c category: #'Add-Ons-LayoutDemo'!
SystemWindow subclass: #LayoutDemo3c
	instanceVariableNames: 'contentArea'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Add-Ons-LayoutDemo'!
!classDefinition: 'LayoutDemo3c class' category: #'Add-Ons-LayoutDemo'!
LayoutDemo3c class
	instanceVariableNames: ''!

!classDefinition: #LayoutDemo3d category: #'Add-Ons-LayoutDemo'!
SystemWindow subclass: #LayoutDemo3d
	instanceVariableNames: 'contentArea'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Add-Ons-LayoutDemo'!
!classDefinition: 'LayoutDemo3d class' category: #'Add-Ons-LayoutDemo'!
LayoutDemo3d class
	instanceVariableNames: ''!

!classDefinition: #LayoutDemo3e category: #'Add-Ons-LayoutDemo'!
SystemWindow subclass: #LayoutDemo3e
	instanceVariableNames: 'contentArea currentContentStringSelector'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Add-Ons-LayoutDemo'!
!classDefinition: 'LayoutDemo3e class' category: #'Add-Ons-LayoutDemo'!
LayoutDemo3e class
	instanceVariableNames: ''!

!classDefinition: #LayoutDemo3f category: #'Add-Ons-LayoutDemo'!
SystemWindow subclass: #LayoutDemo3f
	instanceVariableNames: 'contentArea currentContentStringSelector'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Add-Ons-LayoutDemo'!
!classDefinition: 'LayoutDemo3f class' category: #'Add-Ons-LayoutDemo'!
LayoutDemo3f class
	instanceVariableNames: ''!

!classDefinition: #LayoutDemo3eNotes category: #'Add-Ons-LayoutDemo'!
LayoutDemo3f subclass: #LayoutDemo3eNotes
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Add-Ons-LayoutDemo'!
!classDefinition: 'LayoutDemo3eNotes class' category: #'Add-Ons-LayoutDemo'!
LayoutDemo3eNotes class
	instanceVariableNames: ''!

!classDefinition: #LayoutDemo3fNotes category: #'Add-Ons-LayoutDemo'!
LayoutDemo3f subclass: #LayoutDemo3fNotes
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Add-Ons-LayoutDemo'!
!classDefinition: 'LayoutDemo3fNotes class' category: #'Add-Ons-LayoutDemo'!
LayoutDemo3fNotes class
	instanceVariableNames: ''!

!classDefinition: #LayoutDemo4 category: #'Add-Ons-LayoutDemo'!
SystemWindow subclass: #LayoutDemo4
	instanceVariableNames: 'contentArea'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Add-Ons-LayoutDemo'!
!classDefinition: 'LayoutDemo4 class' category: #'Add-Ons-LayoutDemo'!
LayoutDemo4 class
	instanceVariableNames: ''!

!classDefinition: #LayoutDemo4b category: #'Add-Ons-LayoutDemo'!
SystemWindow subclass: #LayoutDemo4b
	instanceVariableNames: 'contentArea'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Add-Ons-LayoutDemo'!
!classDefinition: 'LayoutDemo4b class' category: #'Add-Ons-LayoutDemo'!
LayoutDemo4b class
	instanceVariableNames: ''!

!classDefinition: #LayoutDemo4c category: #'Add-Ons-LayoutDemo'!
SystemWindow subclass: #LayoutDemo4c
	instanceVariableNames: 'contentArea'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Add-Ons-LayoutDemo'!
!classDefinition: 'LayoutDemo4c class' category: #'Add-Ons-LayoutDemo'!
LayoutDemo4c class
	instanceVariableNames: ''!

!classDefinition: #LayoutDemo5 category: #'Add-Ons-LayoutDemo'!
SystemWindow subclass: #LayoutDemo5
	instanceVariableNames: 'contentArea currentPage pages'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Add-Ons-LayoutDemo'!
!classDefinition: 'LayoutDemo5 class' category: #'Add-Ons-LayoutDemo'!
LayoutDemo5 class
	instanceVariableNames: ''!

!classDefinition: #LayoutDemo5b category: #'Add-Ons-LayoutDemo'!
SystemWindow subclass: #LayoutDemo5b
	instanceVariableNames: 'contentArea currentPage pages'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Add-Ons-LayoutDemo'!
!classDefinition: 'LayoutDemo5b class' category: #'Add-Ons-LayoutDemo'!
LayoutDemo5b class
	instanceVariableNames: ''!

!classDefinition: #LayoutDemo5c category: #'Add-Ons-LayoutDemo'!
SystemWindow subclass: #LayoutDemo5c
	instanceVariableNames: 'contentArea currentPage pages'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Add-Ons-LayoutDemo'!
!classDefinition: 'LayoutDemo5c class' category: #'Add-Ons-LayoutDemo'!
LayoutDemo5c class
	instanceVariableNames: ''!

!classDefinition: #LayoutDemo5d category: #'Add-Ons-LayoutDemo'!
SystemWindow subclass: #LayoutDemo5d
	instanceVariableNames: 'contentArea currentPage pages'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Add-Ons-LayoutDemo'!
!classDefinition: 'LayoutDemo5d class' category: #'Add-Ons-LayoutDemo'!
LayoutDemo5d class
	instanceVariableNames: ''!

!classDefinition: #LayoutDemo5e category: #'Add-Ons-LayoutDemo'!
SystemWindow subclass: #LayoutDemo5e
	instanceVariableNames: 'contentArea currentPage pages'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Add-Ons-LayoutDemo'!
!classDefinition: 'LayoutDemo5e class' category: #'Add-Ons-LayoutDemo'!
LayoutDemo5e class
	instanceVariableNames: ''!

!classDefinition: #LayoutDemo5f category: #'Add-Ons-LayoutDemo'!
SystemWindow subclass: #LayoutDemo5f
	instanceVariableNames: 'contentArea currentPage pages'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Add-Ons-LayoutDemo'!
!classDefinition: 'LayoutDemo5f class' category: #'Add-Ons-LayoutDemo'!
LayoutDemo5f class
	instanceVariableNames: ''!

!classDefinition: #LayoutDemo6 category: #'Add-Ons-LayoutDemo'!
SystemWindow subclass: #LayoutDemo6
	instanceVariableNames: 'contentArea'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Add-Ons-LayoutDemo'!
!classDefinition: 'LayoutDemo6 class' category: #'Add-Ons-LayoutDemo'!
LayoutDemo6 class
	instanceVariableNames: ''!

!classDefinition: #LayoutDemo6b category: #'Add-Ons-LayoutDemo'!
SystemWindow subclass: #LayoutDemo6b
	instanceVariableNames: 'contentArea'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Add-Ons-LayoutDemo'!
!classDefinition: 'LayoutDemo6b class' category: #'Add-Ons-LayoutDemo'!
LayoutDemo6b class
	instanceVariableNames: ''!

!classDefinition: #LayoutDemo6c category: #'Add-Ons-LayoutDemo'!
SystemWindow subclass: #LayoutDemo6c
	instanceVariableNames: 'contentArea'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Add-Ons-LayoutDemo'!
!classDefinition: 'LayoutDemo6c class' category: #'Add-Ons-LayoutDemo'!
LayoutDemo6c class
	instanceVariableNames: ''!

!classDefinition: #LayoutDemo6dABC category: #'Add-Ons-LayoutDemo'!
SystemWindow subclass: #LayoutDemo6dABC
	instanceVariableNames: 'contentArea'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Add-Ons-LayoutDemo'!
!classDefinition: 'LayoutDemo6dABC class' category: #'Add-Ons-LayoutDemo'!
LayoutDemo6dABC class
	instanceVariableNames: ''!

!classDefinition: #ABCbook category: #'Add-Ons-LayoutDemo'!
LayoutDemo6dABC subclass: #ABCbook
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Add-Ons-LayoutDemo'!
!classDefinition: 'ABCbook class' category: #'Add-Ons-LayoutDemo'!
ABCbook class
	instanceVariableNames: ''!

!classDefinition: #LayoutDemo8Timer category: #'Add-Ons-LayoutDemo'!
SystemWindow subclass: #LayoutDemo8Timer
	instanceVariableNames: 'minuteMorphs startTime'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Add-Ons-LayoutDemo'!
!classDefinition: 'LayoutDemo8Timer class' category: #'Add-Ons-LayoutDemo'!
LayoutDemo8Timer class
	instanceVariableNames: ''!


!ABCbook commentStamp: 'hjh 2/11/2013 07:36' prior: 0!
ABCbook open!

!LayoutDemo0 commentStamp: 'hjh 1/16/2013 06:19' prior: 0!
Subclass of SystemWindow. 

Shows how to start building a GUI.
Just sets the window label.

      LayoutDemo0 new openInWorld!

!LayoutDemo1 commentStamp: 'hjh 1/16/2013 06:34' prior: 0!
Subclass of SystemWindow specialised to show how content has to be added.


A SystemWindow instance holds a LayoutMorph instance to which the content has to be added.

This class shows how to do that.



    LayoutDemo1 new openInWorld!

!LayoutDemo1b commentStamp: 'hjh 1/16/2013 06:34' prior: 0!
Subclass of SystemWindow specialised to show how content has to be added.


A SystemWindow instance holds a LayoutMorph instance to which the content has to be added.

This class shows how to do that.



    LayoutDemo1b new openInWorld!

!LayoutDemo2 commentStamp: '<historical>' prior: 0!
Subclass of SystemWindow specialised to show how content has to be added.


   This class shows how to use the #addMorphUseAll: method to use all up the remaining space.



    LayoutDemo2 new openInWorld!

!LayoutDemo2b commentStamp: 'hjh 1/31/2013 04:35' prior: 0!
Subclass of SystemWindow specialised to show how content has to be added.


    With #addMorph:fixedHeight:  a header/title or button bar area may be created.
	
    And with #addMorphUseAll: method all of the remaining space is used..



    LayoutDemo2b new openInWorld!

!LayoutDemo2c commentStamp: 'hjh 1/16/2013 11:19' prior: 0!
Subclass of SystemWindow specialised to show how content has to be added.


   This class shows how to use the #addMorphUseAll: method to use all up the remaining space.

   In addition 
     self beRow.
   is used to put the morphs which are added into a row.



    LayoutDemo2c new openInWorld!

!LayoutDemo2d commentStamp: 'hjh 1/16/2013 11:07' prior: 0!
Subclass of SystemWindow specialised to show how content has to be added.


   This class shows how to use the #addMorphUseAll: method to use all up the remaining space. It as well demonstrates the use of UpdatingStringMorph. They may be used to build a specialized expression watch window.



    LayoutDemo2d new openInWorld!

!LayoutDemo2e commentStamp: 'hjh 1/31/2013 04:41' prior: 0!
Subclass of SystemWindow specialised to show how content has to be added.


   This class shows how to use the #addMorphUseAll: method to use all up the remaining space. It as well demonstrates the use of UpdatingStringMorph. They may be used to build a specialized expression watch window.

Display of the date added.



    LayoutDemo2e new openInWorld!

!LayoutDemo3 commentStamp: 'hjh 1/31/2013 06:30' prior: 0!
Subclass of SystemWindows specialised to display layout examples
add button bar with buttons which change the color of the contentArea morph.

overriding #initialExtent sets the extent of the window.

    LayoutDemo3 new openInWorld!

!LayoutDemo3b commentStamp: 'hjh 1/31/2013 07:13' prior: 0!
Subclass of SystemWindows specialised to display layout examples
Add a TextModelMorph as the content


    LayoutDemo3b new openInWorld!

!LayoutDemo3c commentStamp: 'hjh 2/11/2013 22:33' prior: 0!
Subclass of SystemWindows specialised to display layout examples
Add a TextModelMorph as the content. 

Changed the behaviour of the buttons to change the text.

Works properly if a fix is present in TextModelMorph>>#update:
see http://jvuletich.org/pipermail/cuis_jvuletich.org/2013-February/000827.html


    LayoutDemo3c open!

!LayoutDemo3d commentStamp: '<historical>' prior: 0!
Subclass of SystemWindows specialised to display layout examples
Add a TextModelMorph as the content. 

Changed the behaviour of the buttons to change the text.


    LayoutDemo3d new openInWorld!

!LayoutDemo3e commentStamp: 'hjh 1/31/2013 09:48' prior: 0!
Subclass of SystemWindows specialised to display layout examples

A TextModelMorph as the content. 

Changed the behaviour of the buttons to change the text and automatically save the string in methods.


    LayoutDemo3e new openInWorld!

!LayoutDemo3eNotes commentStamp: 'hjh 1/31/2013 10:46' prior: 0!
A subclass of  LayoutDemo3e

     The changed content strings are stored here.


     LayoutDemo3eNotes new openInWorld!

!LayoutDemo3f commentStamp: 'hjh 1/31/2013 12:20' prior: 0!
Subclass of SystemWindows specialised to display layout examples

A TextModelMorph as the content. 

Changed the behaviour of the buttons to change the text and automatically save the string in methods.


    LayoutDemo3f new openInWorld!

!LayoutDemo3fNotes commentStamp: 'hjh 1/31/2013 12:43' prior: 0!
A subclass of  LayoutDemo3f

     The changed content strings are stored here.


     LayoutDemo3fNotes new openInWorld!

!LayoutDemo4 commentStamp: 'hjh 1/16/2013 09:35' prior: 0!
Subclass of SystemWindows specialised to display layout examples

    LayoutDemo4 new openInWorld!

!LayoutDemo4b commentStamp: 'hjh 1/31/2013 05:07' prior: 0!
Subclass of SystemWindows specialised to display layout examples
Changed from LayoutDemo4: method 
    #makePages


    Adding more morphs to the contentArea without going through the layout morph stacks them on top of each other.

    The button bar changes still the background color of the contentArea morph.


    LayoutDemo4b new openInWorld!

!LayoutDemo4c commentStamp: 'hjh 2/10/2013 16:50' prior: 0!
Subclass of SystemWindows specialised to display layout examples

The pages morphs are stacked on top of each other in the contentArea (RectangleLikeMorph) morph.

The morphs which are added have a #name property set. This allows to call them and bring them to the front. 
This is done with #bringPageToFront:.

The RectangleLikeMorph have been replace by DragAndDropAreaMorph. Morph instances dropped on them stay.


    LayoutDemo4c new openInWorld!

!LayoutDemo5 commentStamp: 'hjh 2/10/2013 16:57' prior: 0!
Subclass of SystemWindows specialised to display layout examples

A more complicated way of achieving the same thing as LayoutDemo4.

Pages are still put on a morph hold in the instance variable contentArea. They are all hidden.

Pages are hold in addition in a separated OrderedCollection, all hidden.
There is a page called the currentPage which is shown.
     LayoutDemo5 new openInWorld!

!LayoutDemo5b commentStamp: '<historical>' prior: 0!
Subclass of SystemWindows specialised to display layout examples

     LayoutDemo5b new openInWorld!

!LayoutDemo5c commentStamp: '<historical>' prior: 0!
Subclass of SystemWindows specialised to display layout examples

     LayoutDemo5c new openInWorld!

!LayoutDemo5d commentStamp: '<historical>' prior: 0!
Subclass of SystemWindows specialised to display layout examples
Hee pages have an individual creation method.
	#createPage1, #createPage2, ...

     LayoutDemo5d new openInWorld!

!LayoutDemo5e commentStamp: '<historical>' prior: 0!
Subclass of SystemWindows specialised to display layout examples

     LayoutDemo6d new openInWorld!

!LayoutDemo5f commentStamp: '<historical>' prior: 0!
Subclass of SystemWindows specialised to display layout examples

     LayoutDemo7 new openInWorld!

!LayoutDemo6 commentStamp: 'hjh 2/10/2013 19:14' prior: 0!
Subclass of SystemWindows specialised to display layout examples
Adapted from LayoutDemo4c. That version only has 7 instance methods whereas 5c has 11 methods.
 
So here again only one instance variable contentArea to hold the pages.

The pages morphs are stacked on top of each other in the contentArea (RectangleLikeMorph) morph.

The morphs which are added have a #name property set. This is used by #bringPageToFront: .

In this demo method #addPageTo:name: aName has been added.

       LayoutDemo6 open!

!LayoutDemo6b commentStamp: 'hjh 2/10/2013 19:14' prior: 0!
Subclass of SystemWindows specialised to display layout examples
The same as LayoutDemo6 but a morph is added centered on each page.

In #addPageTo: name: a LayoutMorph is used.

       LayoutDemo6b open


QUESTION:

| row |
row := LayoutMorph newRow.
row
     color: Color green;
     addMorph: (BorderedRectMorph new 
				color: (Color h: 60 s: 0.6 v: 0.6);
				morphExtent: 170@170).
row padding: #center.
row openInWorld.
row morphExtent: 200@200.
row morphPosition: 150 at 130

If you use a Column and not a Row, you don't even need to specify the 
#padding:, as it defaults to #center.
!

!LayoutDemo6c commentStamp: 'hjh 2/10/2013 19:14' prior: 0!
Subclass of SystemWindows specialised to display layout examples
The same as LayoutDemo6 but a morph is added centered on each page.

In #addPageTo: name: a LayoutMorph is used.

       LayoutDemo6c open


Uses ABC book 



!

!LayoutDemo6dABC commentStamp: '<historical>' prior: 0!
Subclass of SystemWindows specialised to display layout examples
The same as LayoutDemo6 but a morph is added centered on each page.

In #addPageTo: name: a LayoutMorph is used.

       LayoutDemo6dABC open


Uses ABC book 



!

!LayoutDemo8Timer commentStamp: 'hjh 2/2/2013 04:20' prior: 0!
Subclass of SystemWindow specialised to display layout examples

     LayoutDemo8Timer open!

!ABCbook methodsFor: 'as yet unclassified' stamp: 'hjh 2/11/2013 07:43'!
addButtonTo: aMorph name: aName
| aSymbol button |


aSymbol := aName asSymbol.

button := PluggableButtonMorph 
			               model: [ self bringPageToFront: aSymbol]
			               action: #value.
			 
button label: aName first asString font: (
	AbstractFont familyName: 'DejaVu' pointSize: 17
     ).

aMorph addMorph: button fixedWidth: 70! !

!ABCbook class methodsFor: 'as yet unclassified' stamp: 'hjh 2/11/2013 09:20'!
defaultBackgroundColor

	^Color green darker darker! !

!LayoutDemo0 methodsFor: 'GUI building' stamp: 'hjh 1/16/2013 06:22'!
buildMorphicWindow


     self setLabel: self className

	! !

!LayoutDemo0 methodsFor: 'initialization' stamp: 'hjh 1/16/2013 06:16'!
initialize

	super initialize.
	
	self buildMorphicWindow.! !

!LayoutDemo1 methodsFor: 'GUI building' stamp: 'hjh 1/16/2013 06:30'!
buildMorphicWindow


     	self setLabel: self className.

	self layoutMorph  addMorph: 
	   (RectangleLikeMorph new color: Color yellow) fixedHeight: 80.
	
 	self layoutMorph  addMorph: 
	   (RectangleLikeMorph new color: Color green) fixedHeight: 80.
 
	self layoutMorph  addMorph: 
	   (RectangleLikeMorph new color: Color red) fixedHeight: 80! !

!LayoutDemo1 methodsFor: 'initialization' stamp: 'hjh 1/16/2013 06:20'!
initialize

	super initialize.
	
	self buildMorphicWindow.! !

!LayoutDemo1b methodsFor: 'GUI building' stamp: 'hjh 1/31/2013 04:31'!
buildMorphicWindow


     	self setLabel: self className.

      self layoutMorph beRow.
     "or
      self beRow."

	self layoutMorph  addMorph: 
	   (RectangleLikeMorph new color: Color yellow).
	
 	self layoutMorph  addMorph: 
	   (DragAndDropAreaMorph new color: Color green).
 
	self layoutMorph  addMorph: 
	   (RectangleLikeMorph new color: Color red).! !

!LayoutDemo1b methodsFor: 'initialization' stamp: 'hjh 1/16/2013 06:20'!
initialize

	super initialize.
	
	self buildMorphicWindow.! !

!LayoutDemo2 methodsFor: 'GUI building' stamp: 'hjh 1/16/2013 11:02'!
buildMorphicWindow


     	self setLabel: self className.

	self layoutMorph  addMorphUseAll: 
	   (RectangleLikeMorph new color: Color red).

	self layoutMorph  addMorphUseAll: 
	   (RectangleLikeMorph new color: Color yellow).
	
 	self layoutMorph  addMorphUseAll: 
	   (RectangleLikeMorph new color: Color green) 
 
	! !

!LayoutDemo2 methodsFor: 'initialization' stamp: 'hjh 1/16/2013 06:20'!
initialize

	super initialize.
	
	self buildMorphicWindow.! !

!LayoutDemo2b methodsFor: 'GUI building' stamp: 'hjh 1/16/2013 06:57'!
buildMorphicWindow


     	self setLabel: self className.

	self layoutMorph  addMorph: 
	   (RectangleLikeMorph new color: Color yellow) fixedHeight: 80.
	
 	self layoutMorph  addMorphUseAll: 
	   (RectangleLikeMorph new color: Color green) 
 
	! !

!LayoutDemo2b methodsFor: 'initialization' stamp: 'hjh 1/16/2013 06:20'!
initialize

	super initialize.
	
	self buildMorphicWindow.! !

!LayoutDemo2c methodsFor: 'GUI building' stamp: 'hjh 1/16/2013 11:18'!
buildMorphicWindow


     	self setLabel: self className.
	
	self beRow.

	self layoutMorph  addMorphUseAll: 
	   (RectangleLikeMorph new color: Color red).

	self layoutMorph  addMorphUseAll: 
	   (RectangleLikeMorph new color: Color yellow).
	
 	self layoutMorph  addMorphUseAll: 
	   (RectangleLikeMorph new color: Color green) 
 
	! !

!LayoutDemo2c methodsFor: 'initialization' stamp: 'hjh 1/16/2013 06:20'!
initialize

	super initialize.
	
	self buildMorphicWindow.! !

!LayoutDemo2d methodsFor: 'GUI building' stamp: 'hjh 1/31/2013 04:40'!
buildMorphicWindow


     	self setLabel: self className.

	self layoutMorph  
	 addMorph: 
	    ((UpdatingStringMorph new
      			target: ['Cursor position: ',
				            self runningWorld activeHand morphPosition asString
				           ];
		            getSelector: #value;
     			      stepTime: 10) color: Color blue).
	
	self layoutMorph  addMorphUseAll: 
	   (RectangleLikeMorph new color: Color green). 
 
	
 	self layoutMorph  addMorph: 
	   (UpdatingStringMorph new
      			target: ['self morphBoundsInWorld ',
				            self morphBoundsInWorld asString];
		            getSelector: #value;
     			      stepTime: 10) 
	fixedHeight: 60.
 
	! !

!LayoutDemo2d methodsFor: 'initialization' stamp: 'hjh 1/31/2013 04:38'!
initialize

	super initialize.
	
	self buildMorphicWindow.
	! !

!LayoutDemo2e methodsFor: 'GUI building' stamp: 'hjh 1/31/2013 04:43'!
buildMorphicWindow


     	self setLabel: self className.

	self layoutMorph  
	 addMorph: 
	    ((UpdatingStringMorph new
      			target: ['Cursor position: ',
				            self runningWorld activeHand morphPosition asString
				           ];
		            getSelector: #value;
     			      stepTime: 10) color: Color blue) 
	 fixedHeight: 80.
	
	self layoutMorph  addMorphUseAll: 
	   (RectangleLikeMorph new color: Color green). 
	
 	self layoutMorph  addMorph: 
	   (UpdatingStringMorph new
      			target: ['self morphBoundsInWorld ',
				            self morphBoundsInWorld asString];
		            getSelector: #value;
     			      stepTime: 10). 
 
 	self layoutMorph  addMorph: 
	   (UpdatingStringMorph new
      			target: [Date today asString];
		            getSelector: #value;
     			      stepTime: 10) 
	 fixedHeight: 30.
	! !

!LayoutDemo2e methodsFor: 'initialization' stamp: 'hjh 1/16/2013 11:11'!
initialize

	super initialize.
	
	self buildMorphicWindow.
	! !

!LayoutDemo3 methodsFor: 'GUI building' stamp: 'hjh 1/31/2013 06:32'!
buildMorphicWindow

self setLabel: self className.

contentArea := RectangleLikeMorph new color: Color green.


self layoutMorph addMorph:  self createButtonBar fixedHeight: 40.
self layoutMorph addMorphUseAll: contentArea.

self openInWorld

! !

!LayoutDemo3 methodsFor: 'GUI building' stamp: 'hjh 1/16/2013 10:48'!
createButtonBar

^ LayoutMorph newRow 
    addMorph: 
        (PluggableButtonMorph 
			model: [ contentArea color: Color red] action: #value label: 'red'
	  ) 
    fixedWidth: 70;
	
    addMorph: 
      (PluggableButtonMorph 
			model: [ contentArea color: Color green] action: #value label: 'green'
	) 
    fixedWidth: 70;
	
    addMorph: 
       (PluggableButtonMorph 
			model: [ contentArea color: Color blue] action: #value label: 'blue'
	 ) 
	 fixedWidth: 70;
      
    addMorph: 
       (PluggableButtonMorph 
			model: [ contentArea color: Color yellow] action: #value label: 'yellow'
	 ) 
	fixedWidth: 70
	! !

!LayoutDemo3 methodsFor: 'initialization' stamp: 'hjh 1/31/2013 06:30'!
initialExtent
	
	
	^ 480 @ 360! !

!LayoutDemo3 methodsFor: 'initialization' stamp: 'hjh 1/12/2013 11:18'!
initialize

	super initialize.
	self buildMorphicWindow.! !

!LayoutDemo3 methodsFor: 'GUI building' stamp: 'hjh 1/12/2013 11:21'!
initializeLabelArea
	"Initialize the label area (titlebar) for the window.
	This is a shorter version of inherited #initializeLabelArea.
	We do not create the other controls"

	|  box |

	box _ self createCloseBox.
	self addMorph: box.
	box morphPosition: 2@2.
	box morphExtent: self boxExtent.

! !

!LayoutDemo3b methodsFor: 'GUI building' stamp: 'hjh 1/31/2013 07:14'!
buildMorphicWindow

self setLabel: self className.

contentArea := TextModelMorph withText: 'abc...'.


self layoutMorph addMorph:  self createButtonBar fixedHeight: 40.
self layoutMorph addMorphUseAll: contentArea.

self openInWorld

! !

!LayoutDemo3b methodsFor: 'GUI building' stamp: 'hjh 1/16/2013 10:48'!
createButtonBar

^ LayoutMorph newRow 
    addMorph: 
        (PluggableButtonMorph 
			model: [ contentArea color: Color red] action: #value label: 'red'
	  ) 
    fixedWidth: 70;
	
    addMorph: 
      (PluggableButtonMorph 
			model: [ contentArea color: Color green] action: #value label: 'green'
	) 
    fixedWidth: 70;
	
    addMorph: 
       (PluggableButtonMorph 
			model: [ contentArea color: Color blue] action: #value label: 'blue'
	 ) 
	 fixedWidth: 70;
      
    addMorph: 
       (PluggableButtonMorph 
			model: [ contentArea color: Color yellow] action: #value label: 'yellow'
	 ) 
	fixedWidth: 70
	! !

!LayoutDemo3b methodsFor: 'initialization' stamp: 'hjh 1/31/2013 06:30'!
initialExtent
	
	
	^ 480 @ 360! !

!LayoutDemo3b methodsFor: 'initialization' stamp: 'hjh 1/12/2013 11:18'!
initialize

	super initialize.
	self buildMorphicWindow.! !

!LayoutDemo3b methodsFor: 'GUI building' stamp: 'hjh 1/12/2013 11:21'!
initializeLabelArea
	"Initialize the label area (titlebar) for the window.
	This is a shorter version of inherited #initializeLabelArea.
	We do not create the other controls"

	|  box |

	box _ self createCloseBox.
	self addMorph: box.
	box morphPosition: 2@2.
	box morphExtent: self boxExtent.

! !

!LayoutDemo3c methodsFor: 'GUI building' stamp: 'hjh 1/31/2013 07:14'!
buildMorphicWindow

self setLabel: self className.

contentArea := TextModelMorph withText: 'abc...'.


self layoutMorph addMorph:  self createButtonBar fixedHeight: 40.
self layoutMorph addMorphUseAll: contentArea.

self openInWorld

! !

!LayoutDemo3c methodsFor: 'GUI building' stamp: 'hjh 2/11/2013 22:28'!
createButtonBar

^ LayoutMorph newRow 
    addMorph: 
        (PluggableButtonMorph 
			model: [ contentArea model actualContents:  'red'] action: #value label: 'red'
	  ) 
    fixedWidth: 70;
	
    addMorph: 
      (PluggableButtonMorph 
			model: [ contentArea model actualContents: 'green'] action: #value label: 'green'
	) 
    fixedWidth: 70;
	
    addMorph: 
       (PluggableButtonMorph 
			model: [ contentArea model actualContents: 'blue'] action: #value label: 'blue'
	 ) 
	 fixedWidth: 70;
      
    addMorph: 
       (PluggableButtonMorph 
			model: [ contentArea model actualContents: 'yellow'] action: #value label: 'yellow'
	 ) 
	fixedWidth: 70
	! !

!LayoutDemo3c methodsFor: 'initialization' stamp: 'hjh 1/31/2013 06:30'!
initialExtent
	
	
	^ 480 @ 360! !

!LayoutDemo3c methodsFor: 'initialization' stamp: 'hjh 1/12/2013 11:18'!
initialize

	super initialize.
	self buildMorphicWindow.! !

!LayoutDemo3c methodsFor: 'GUI building' stamp: 'hjh 1/12/2013 11:21'!
initializeLabelArea
	"Initialize the label area (titlebar) for the window.
	This is a shorter version of inherited #initializeLabelArea.
	We do not create the other controls"

	|  box |

	box _ self createCloseBox.
	self addMorph: box.
	box morphPosition: 2@2.
	box morphExtent: self boxExtent.

! !

!LayoutDemo3c class methodsFor: 'as yet unclassified' stamp: 'hjh 2/11/2013 22:32'!
open
	^self new openInWorld! !

!LayoutDemo3d methodsFor: 'GUI building' stamp: 'hjh 1/31/2013 08:40'!
buildMorphicWindow

self setLabel: self className.

contentArea := self textModelMorphforSelector:  #contentString1.

self layoutMorph addMorph:  self createButtonBar fixedHeight: 40.
self layoutMorph addMorphUseAll: contentArea.

self openInWorld

! !

!LayoutDemo3d methodsFor: 'content' stamp: 'hjh 1/31/2013 08:31'!
contentString1
	^'hello1'! !

!LayoutDemo3d methodsFor: 'content' stamp: 'hjh 1/31/2013 08:31'!
contentString2
	^'hello2'! !

!LayoutDemo3d methodsFor: 'content' stamp: 'hjh 1/31/2013 08:31'!
contentString3
	^'hello3'! !

!LayoutDemo3d methodsFor: 'content' stamp: 'hjh 1/31/2013 08:31'!
contentString4
	^'hello4'! !

!LayoutDemo3d methodsFor: 'GUI building' stamp: 'hjh 1/31/2013 08:32'!
createButtonBar

^ LayoutMorph newRow 
    addMorph: 
        (PluggableButtonMorph 
			model: [ self display: #contentString1 ] action: #value label: 'red'
	  ) 
    fixedWidth: 70;
	
    addMorph: 
      (PluggableButtonMorph 
			model: [ self display: #contentString2 ] action: #value label: 'green'
	) 
    fixedWidth: 70;
	
    addMorph: 
       (PluggableButtonMorph 
			model: [ self display: #contentString3 ] action: #value label: 'blue'
	 ) 
	 fixedWidth: 70;
      
    addMorph: 
       (PluggableButtonMorph 
			model: [ self display: #contentString4 ] action: #value label: 'yellow'
	 ) 
	fixedWidth: 70
	! !

!LayoutDemo3d methodsFor: 'content' stamp: 'hjh 1/31/2013 08:43'!
display: aContentSelector

	self layoutMorph removeMorph: contentArea.
	self layoutMorph addMorphUseAll: (contentArea := self textModelMorphforSelector:  aContentSelector)
	! !

!LayoutDemo3d methodsFor: 'initialization' stamp: 'hjh 1/31/2013 06:30'!
initialExtent
	
	
	^ 480 @ 360! !

!LayoutDemo3d methodsFor: 'initialization' stamp: 'hjh 1/12/2013 11:18'!
initialize

	super initialize.
	self buildMorphicWindow.! !

!LayoutDemo3d methodsFor: 'GUI building' stamp: 'hjh 1/12/2013 11:21'!
initializeLabelArea
	"Initialize the label area (titlebar) for the window.
	This is a shorter version of inherited #initializeLabelArea.
	We do not create the other controls"

	|  box |

	box _ self createCloseBox.
	self addMorph: box.
	box morphPosition: 2@2.
	box morphExtent: self boxExtent.

! !

!LayoutDemo3d methodsFor: 'content' stamp: 'hjh 1/31/2013 08:37'!
textModelMorphforSelector: aContentSelector

	^TextModelMorph withText: (self perform: aContentSelector)
	! !

!LayoutDemo3e methodsFor: 'GUI building' stamp: 'hjh 1/31/2013 10:43'!
buildMorphicWindow

self setLabel: self titleString.

contentArea := self textModelMorphforSelector:  #contentString1.
currentContentStringSelector := #contentString1.


self layoutMorph addMorph:  self createButtonBar fixedHeight: 40.
self layoutMorph addMorphUseAll: contentArea.

self openInWorld

! !

!LayoutDemo3e methodsFor: 'content' stamp: 'hjh 1/31/2013 09:49'!
contentString1
	^ 'This is the red content area.

   You may edit this text and 
   when you press another button it will be  saved.'! !

!LayoutDemo3e methodsFor: 'content' stamp: 'hjh 1/31/2013 09:49'!
contentString2
	^ 'green'! !

!LayoutDemo3e methodsFor: 'content' stamp: 'hjh 1/31/2013 09:49'!
contentString3
	^ 'blue'! !

!LayoutDemo3e methodsFor: 'content' stamp: 'hjh 1/31/2013 09:49'!
contentString4
	^ 'yellow'! !

!LayoutDemo3e methodsFor: 'GUI building' stamp: 'hjh 1/31/2013 09:40'!
createButtonBar

| bar |

^ (bar :=LayoutMorph newRow color: Color red) 
    addMorph: 
        (PluggableButtonMorph 
			model: [ self display: #contentString1.
				        bar color: Color red] action: #value label: 'red'
	  ) 
    fixedWidth: 70;
	
    addMorph: 
      (PluggableButtonMorph 
			model: [ self display: #contentString2.
				       bar color: Color green] action: #value label: 'green'
	) 
    fixedWidth: 70;
	
    addMorph: 
       (PluggableButtonMorph 
			model: [ self display: #contentString3.
				  bar color: Color blue ] action: #value label: 'blue'
	 ) 
	 fixedWidth: 70;
      
    addMorph: 
       (PluggableButtonMorph 
			model: [ self display: #contentString4.
				  bar color: Color yellow ] action: #value label: 'yellow'
	 ) 
	fixedWidth: 70
	! !

!LayoutDemo3e methodsFor: 'content manipulation' stamp: 'hjh 1/31/2013 09:29'!
display: aContentSelector

	currentContentStringSelector ifNotNil:  [self removeOldContent].
	
	currentContentStringSelector := aContentSelector.
	
	self layoutMorph addMorphUseAll: 
		(contentArea := self textModelMorphforSelector:  currentContentStringSelector)
	! !

!LayoutDemo3e methodsFor: 'initialization' stamp: 'hjh 1/31/2013 06:30'!
initialExtent
	
	
	^ 480 @ 360! !

!LayoutDemo3e methodsFor: 'initialization' stamp: 'hjh 1/12/2013 11:18'!
initialize

	super initialize.
	self buildMorphicWindow.! !

!LayoutDemo3e methodsFor: 'GUI building' stamp: 'hjh 1/12/2013 11:21'!
initializeLabelArea
	"Initialize the label area (titlebar) for the window.
	This is a shorter version of inherited #initializeLabelArea.
	We do not create the other controls"

	|  box |

	box _ self createCloseBox.
	self addMorph: box.
	box morphPosition: 2@2.
	box morphExtent: self boxExtent.

! !

!LayoutDemo3e methodsFor: 'content manipulation' stamp: 'hjh 1/31/2013 09:35'!
removeOldContent
"save the old content in a method first and then remove the text morph"

  | methodSource |

  methodSource :=

		 	currentContentStringSelector asString
			
			, String newLineString 
			
			,'	^ ''' ,
			
			contentArea model actualContents asString,
			
			''''.
   self class compile: methodSource.
			
   self layoutMorph removeMorph: contentArea.! !

!LayoutDemo3e methodsFor: 'content manipulation' stamp: 'hjh 1/31/2013 08:37'!
textModelMorphforSelector: aContentSelector

	^TextModelMorph withText: (self perform: aContentSelector)
	! !

!LayoutDemo3e methodsFor: 'initialization' stamp: 'hjh 1/31/2013 10:43'!
titleString

	^ self className! !

!LayoutDemo3eNotes methodsFor: 'as yet unclassified' stamp: 'hjh 1/31/2013 11:18'!
contentString1
	^ 'This is the red content area.

   You may edit this text and 
   when you press another button it will be  saved.


'! !

!LayoutDemo3eNotes methodsFor: 'as yet unclassified' stamp: 'hjh 1/31/2013 11:18'!
contentString2
	^ 'green area

A sample note
------------------

https://help.github.com/articles/interactive-rebase


 git rebase --interactive'! !

!LayoutDemo3eNotes methodsFor: 'as yet unclassified' stamp: 'hjh 1/31/2013 11:18'!
contentString3
	^ 'blue notes area'! !

!LayoutDemo3eNotes methodsFor: 'as yet unclassified' stamp: 'hjh 1/31/2013 11:18'!
contentString4
	^ 'yellow notes area'! !

!LayoutDemo3eNotes methodsFor: 'as yet unclassified' stamp: 'hjh 1/31/2013 10:44'!
titleString

	^ 'Notes'! !

!LayoutDemo3f methodsFor: 'GUI building' stamp: 'hjh 1/31/2013 12:35'!
buildMorphicWindow

self setLabel: self titleString.

contentArea := self textModelMorphforSelector:  #contentString1.
currentContentStringSelector := #contentString1.


self layoutMorph addMorph:  (self createButtonBarFromSpec: self customButtonSpecs) fixedHeight: 40.
self layoutMorph addMorphUseAll: contentArea.

self openInWorld

! !

!LayoutDemo3f methodsFor: 'content' stamp: 'hjh 1/31/2013 12:41'!
contentString1
	^ 'This is the red content area.

   You may edit this text and 
   when you press another button it will be  saved.'! !

!LayoutDemo3f methodsFor: 'content' stamp: 'hjh 1/31/2013 12:42'!
contentString2
	^ 'green'! !

!LayoutDemo3f methodsFor: 'content' stamp: 'hjh 1/31/2013 12:42'!
contentString3
	^ 'blue'! !

!LayoutDemo3f methodsFor: 'content' stamp: 'hjh 1/31/2013 12:42'!
contentString4
	^ 'yellow'! !

!LayoutDemo3f methodsFor: 'content' stamp: 'hjh 1/31/2013 12:42'!
contentString5
	^ 'This is the red content area.

   You may edit this text and 
   when you press another button it will be  saved.'! !

!LayoutDemo3f methodsFor: 'content' stamp: 'hjh 1/31/2013 12:42'!
contentString6
	^ 'This is the red content area.

   You may edit this text and 
   when you press another button it will be  saved.'! !

!LayoutDemo3f methodsFor: 'GUI building' stamp: 'hjh 1/31/2013 13:15'!
createButtonBarFromSpec: aButtonCollectionSpec

| bar |

bar :=LayoutMorph newRow color: Color red.

aButtonCollectionSpec do: [ :buttonSpec |
    bar addMorph: 
        (PluggableButtonMorph 
			model: [ self display: (buttonSpec at: 2).
				        bar color: (Color perform: (buttonSpec at: 3))] 
			action: #value label: (buttonSpec at: 1)
	  ) 
    fixedWidth: self defaultButtonWidth].

^ bar! !

!LayoutDemo3f methodsFor: 'GUI building' stamp: 'hjh 1/31/2013 12:41'!
customButtonSpecs
	"Answer an array of elements of the label, selector and color"

	^#(
		('red'			#contentString1			     #lightRed)
		('green'			#contentString2			     #lightGreen)
		('blue'			#contentString3			     #lightBlue)
		('yellow'		#contentString4		           #yellow)
		('orange'		#contentString5		           #orange)
		('magenta'		#contentString6		           #magenta)
	)

  
! !

!LayoutDemo3f methodsFor: 'GUI building' stamp: 'hjh 1/31/2013 13:16'!
defaultButtonWidth
	^70! !

!LayoutDemo3f methodsFor: 'content manipulation' stamp: 'hjh 1/31/2013 09:29'!
display: aContentSelector

	currentContentStringSelector ifNotNil:  [self removeOldContent].
	
	currentContentStringSelector := aContentSelector.
	
	self layoutMorph addMorphUseAll: 
		(contentArea := self textModelMorphforSelector:  currentContentStringSelector)
	! !

!LayoutDemo3f methodsFor: 'initialization' stamp: 'hjh 1/31/2013 06:30'!
initialExtent
	
	
	^ 480 @ 360! !

!LayoutDemo3f methodsFor: 'initialization' stamp: 'hjh 1/12/2013 11:18'!
initialize

	super initialize.
	self buildMorphicWindow.! !

!LayoutDemo3f methodsFor: 'GUI building' stamp: 'hjh 1/12/2013 11:21'!
initializeLabelArea
	"Initialize the label area (titlebar) for the window.
	This is a shorter version of inherited #initializeLabelArea.
	We do not create the other controls"

	|  box |

	box _ self createCloseBox.
	self addMorph: box.
	box morphPosition: 2@2.
	box morphExtent: self boxExtent.

! !

!LayoutDemo3f methodsFor: 'content manipulation' stamp: 'hjh 1/31/2013 09:35'!
removeOldContent
"save the old content in a method first and then remove the text morph"

  | methodSource |

  methodSource :=

		 	currentContentStringSelector asString
			
			, String newLineString 
			
			,'	^ ''' ,
			
			contentArea model actualContents asString,
			
			''''.
   self class compile: methodSource.
			
   self layoutMorph removeMorph: contentArea.! !

!LayoutDemo3f methodsFor: 'content manipulation' stamp: 'hjh 1/31/2013 08:37'!
textModelMorphforSelector: aContentSelector

	^TextModelMorph withText: (self perform: aContentSelector)
	! !

!LayoutDemo3f methodsFor: 'initialization' stamp: 'hjh 1/31/2013 10:43'!
titleString

	^ self className! !

!LayoutDemo3fNotes methodsFor: 'content' stamp: 'hjh 1/31/2013 13:17'!
contentString1
	^ 'This is the red content area.

   You may edit this text and 
   when you press another button it will be  saved.'! !

!LayoutDemo3fNotes methodsFor: 'content' stamp: 'hjh 1/31/2013 13:17'!
contentString2
	^ 'green'! !

!LayoutDemo3fNotes methodsFor: 'content' stamp: 'hjh 1/31/2013 13:17'!
contentString3
	^ 'blue'! !

!LayoutDemo3fNotes methodsFor: 'content' stamp: 'hjh 1/31/2013 13:17'!
contentString4
	^ 'yellow'! !

!LayoutDemo3fNotes methodsFor: 'content' stamp: 'hjh 1/31/2013 13:17'!
contentString5
	^ 'orange
'! !

!LayoutDemo3fNotes methodsFor: 'content' stamp: 'hjh 1/31/2013 13:17'!
contentString6
	^ 'magenta'! !

!LayoutDemo3fNotes methodsFor: 'content' stamp: 'hjh 1/31/2013 13:17'!
contentString7
	^ 'brown'! !

!LayoutDemo3fNotes methodsFor: 'as yet unclassified' stamp: 'hjh 1/31/2013 13:13'!
customButtonSpecs
	"Answer an array of elements of the label, selector and color"

	^#(
		('1'			#contentString1			     #lightRed)
		('2'			#contentString2			     #lightGreen)
		('3'			#contentString3			     #lightBlue)
		('4'		      #contentString4		           #yellow)
		('5'		      #contentString5		           #orange)
		('6'		      #contentString6		           #magenta)
		('7'		      #contentString7		           #brown)
	)

  ! !

!LayoutDemo3fNotes methodsFor: 'as yet unclassified' stamp: 'hjh 1/31/2013 13:16'!
defaultButtonWidth
	^50! !

!LayoutDemo3fNotes methodsFor: 'as yet unclassified' stamp: 'hjh 1/31/2013 13:16'!
initialExtent

^ 400 @ 500! !

!LayoutDemo3fNotes methodsFor: 'as yet unclassified' stamp: 'hjh 1/31/2013 12:44'!
titleString

	^ 'Notes'! !

!LayoutDemo4 methodsFor: 'GUI building' stamp: 'hjh 1/31/2013 04:49'!
buildMorphicWindow

self setLabel: self className.


self layoutMorph addMorph:  self createButtonBar fixedHeight: 60.
self layoutMorph addMorphUseAll: self makeContentArea.

self openInWorld
! !

!LayoutDemo4 methodsFor: 'GUI building' stamp: 'hjh 1/12/2013 11:51'!
createButtonBar


^ LayoutMorph newRow 
	
addMorph: (PluggableButtonMorph 
			model: [ contentArea color: Color red] action: #value label: 'red') 
	            fixedWidth: 70;
	
addMorph: (PluggableButtonMorph 
			model: [ contentArea color: Color green] action: #value label: 'green') 
	           fixedWidth: 70;
	
addMorph: (PluggableButtonMorph 
			model: [ contentArea color: Color blue] action: #value label: 'blue') 
	           fixedWidth: 70;

addMorph: (PluggableButtonMorph 
			model: [ contentArea color: Color yellow] action: #value label: 'yellow') 
	           fixedWidth: 70! !

!LayoutDemo4 methodsFor: 'initialization' stamp: 'hjh 1/31/2013 06:32'!
initialExtent
	
	
	^ 480 @ 360! !

!LayoutDemo4 methodsFor: 'initialization' stamp: 'hjh 1/12/2013 11:18'!
initialize

	super initialize.
	self buildMorphicWindow.! !

!LayoutDemo4 methodsFor: 'GUI building' stamp: 'hjh 1/12/2013 11:21'!
initializeLabelArea
	"Initialize the label area (titlebar) for the window.
	This is a shorter version of inherited #initializeLabelArea.
	We do not create the other controls"

	|  box |

	box _ self createCloseBox.
	self addMorph: box.
	box morphPosition: 2@2.
	box morphExtent: self boxExtent.

! !

!LayoutDemo4 methodsFor: 'page creation' stamp: 'hjh 1/31/2013 04:49'!
makeContentArea


      ^contentArea := RectangleLikeMorph new color: Color green.! !

!LayoutDemo4b methodsFor: 'GUI building' stamp: 'hjh 1/31/2013 06:33'!
buildMorphicWindow

self setLabel: self className.


self layoutMorph addMorph:  self createButtonBar fixedHeight: 40.
self layoutMorph addMorphUseAll: self makePages.

self openInWorld
! !

!LayoutDemo4b methodsFor: 'GUI building' stamp: 'hjh 1/12/2013 11:51'!
createButtonBar


^ LayoutMorph newRow 
	
addMorph: (PluggableButtonMorph 
			model: [ contentArea color: Color red] action: #value label: 'red') 
	            fixedWidth: 70;
	
addMorph: (PluggableButtonMorph 
			model: [ contentArea color: Color green] action: #value label: 'green') 
	           fixedWidth: 70;
	
addMorph: (PluggableButtonMorph 
			model: [ contentArea color: Color blue] action: #value label: 'blue') 
	           fixedWidth: 70;

addMorph: (PluggableButtonMorph 
			model: [ contentArea color: Color yellow] action: #value label: 'yellow') 
	           fixedWidth: 70! !

!LayoutDemo4b methodsFor: 'initialization' stamp: 'hjh 1/31/2013 06:32'!
initialExtent
	
	
	^ 480 @ 360! !

!LayoutDemo4b methodsFor: 'initialization' stamp: 'hjh 1/12/2013 11:18'!
initialize

	super initialize.
	self buildMorphicWindow.! !

!LayoutDemo4b methodsFor: 'GUI building' stamp: 'hjh 1/12/2013 11:21'!
initializeLabelArea
	"Initialize the label area (titlebar) for the window.
	This is a shorter version of inherited #initializeLabelArea.
	We do not create the other controls"

	|  box |

	box _ self createCloseBox.
	self addMorph: box.
	box morphPosition: 2@2.
	box morphExtent: self boxExtent.

! !

!LayoutDemo4b methodsFor: 'page creation' stamp: 'hjh 1/31/2013 05:09'!
makePages

 	contentArea := RectangleLikeMorph new color: Color gray.
	

      contentArea addMorph: ((RectangleLikeMorph new color: Color red) morphExtent: 320@240).
								
	contentArea addMorph: ((RectangleLikeMorph new color: Color green)  morphExtent: 310@230).
								
	contentArea addMorph: ((RectangleLikeMorph new color: Color blue)  morphExtent: 305@225).
	
	contentArea addMorph: ((RectangleLikeMorph new color: Color yellow)  morphExtent: 300@220).
	
	^ contentArea


    ! !

!LayoutDemo4c methodsFor: 'pages' stamp: 'hjh 1/31/2013 05:20'!
bringPageToFront: aPageName

 	| page |
	
	page := contentArea submorphs detect: [ :morph | (morph valueOfProperty: #name) = aPageName].
	
	contentArea addMorphFront: page. 
	


! !

!LayoutDemo4c methodsFor: 'GUI building' stamp: 'hjh 1/31/2013 07:05'!
buildMorphicWindow

self setLabel: self className.


self layoutMorph addMorph:  self createButtonBar fixedHeight: 40.
self layoutMorph addMorphUseAll: self makeContentArea.

self openInWorld
! !

!LayoutDemo4c methodsFor: 'GUI building' stamp: 'hjh 1/31/2013 05:17'!
createButtonBar


^ LayoutMorph newRow 
	
addMorph: (PluggableButtonMorph 
			model: [ self bringPageToFront: #red] action: #value label: 'red') 
	            fixedWidth: 70;
	
addMorph: (PluggableButtonMorph 
			model: [ self  bringPageToFront: #green] action: #value label: 'green') 
	           fixedWidth: 70;
	
addMorph: (PluggableButtonMorph 
			model: [ self bringPageToFront: #blue] action: #value label: 'blue') 
	           fixedWidth: 70;

addMorph: (PluggableButtonMorph 
			model: [ self bringPageToFront: #yellow] action: #value label: 'yellow') 
	           fixedWidth: 70! !

!LayoutDemo4c methodsFor: 'initialization' stamp: 'hjh 1/31/2013 06:33'!
initialExtent
	
	
	^ 480 @ 360! !

!LayoutDemo4c methodsFor: 'initialization' stamp: 'hjh 1/12/2013 11:18'!
initialize

	super initialize.
	self buildMorphicWindow.! !

!LayoutDemo4c methodsFor: 'GUI building' stamp: 'hjh 1/12/2013 11:21'!
initializeLabelArea
	"Initialize the label area (titlebar) for the window.
	This is a shorter version of inherited #initializeLabelArea.
	We do not create the other controls"

	|  box |

	box _ self createCloseBox.
	self addMorph: box.
	box morphPosition: 2@2.
	box morphExtent: self boxExtent.

! !

!LayoutDemo4c methodsFor: 'pages' stamp: 'hjh 1/31/2013 07:06'!
makeContentArea

 	contentArea := RectangleLikeMorph new color: Color gray.  "This morph does not do layout control"

	"morphs are added on top of each other"

      contentArea addMorph: ((DragAndDropAreaMorph new color: Color red;
								setProperty: #name toValue: #red) morphExtent: 430@250).
								
	contentArea addMorph: ((DragAndDropAreaMorph new color: Color green;
								setProperty: #name toValue: #green)  morphExtent: 420@240).
								
	contentArea addMorph: ((DragAndDropAreaMorph new color: Color blue;
								setProperty: #name toValue: #blue)  morphExtent: 410@230).
	
	contentArea addMorph: ((DragAndDropAreaMorph new color: Color yellow;
							     setProperty: #name toValue: #yellow)  morphExtent: 400@220).
	
	
	
	^ contentArea


    ! !

!LayoutDemo5 methodsFor: 'GUI building' stamp: 'hjh 1/16/2013 12:40'!
buildMorphicWindow


  self layoutMorph addMorph: self createButtonBar fixedHeight: 40.  self layoutMorph addMorphUseAll: self makePages.
  self setLabel: self className.
  self openInWorld.

  currentPage := 1.

  self displayPage: currentPage.
! !

!LayoutDemo5 methodsFor: 'GUI building' stamp: 'hjh 1/12/2013 12:37'!
createButtonBar


^ LayoutMorph newRow 
	
addMorph: (PluggableButtonMorph 
			model: [ self showPage: 1] action: #value label: 'red') 
	            fixedWidth: 70;
	
addMorph: (PluggableButtonMorph 
			model: [ self showPage: 2] action: #value label: 'green') 
	           fixedWidth: 70;
	
addMorph: (PluggableButtonMorph 
			model: [ self showPage: 3] action: #value label: 'blue') 
	           fixedWidth: 70;

addMorph: (PluggableButtonMorph 
			model: [ self showPage: 4] action: #value label: 'yellow') 
	           fixedWidth: 70! !

!LayoutDemo5 methodsFor: 'page display' stamp: 'hjh 1/12/2013 12:18'!
displayPage: pageNumber
	| page |
	"self adjustButtonsForPage: pageNumber."
	page := pages at: pageNumber.
	page show! !

!LayoutDemo5 methodsFor: 'page display' stamp: 'hjh 1/12/2013 12:35'!
hideCurrentPage
	| page |
	page := pages at: currentPage.
	page hide! !

!LayoutDemo5 methodsFor: 'initialization' stamp: 'hjh 1/12/2013 11:18'!
initialize

	super initialize.
	self buildMorphicWindow.! !

!LayoutDemo5 methodsFor: 'GUI building' stamp: 'hjh 1/12/2013 11:21'!
initializeLabelArea
	"Initialize the label area (titlebar) for the window.
	This is a shorter version of inherited #initializeLabelArea.
	We do not create the other controls"

	|  box |

	box _ self createCloseBox.
	self addMorph: box.
	box morphPosition: 2@2.
	box morphExtent: self boxExtent.

! !

!LayoutDemo5 methodsFor: 'page creation' stamp: 'hjh 1/16/2013 14:04'!
makePages
	| contentArea |
	pages := OrderedCollection new.
	pages add: ((RectangleLikeMorph new color: Color red) morphExtent: 320@240).
	pages add: ((RectangleLikeMorph new color: Color green)  morphExtent: 310@230).
	pages add: ((RectangleLikeMorph new color: Color blue)  morphExtent: 305@225).
	pages add: ((RectangleLikeMorph new color: Color yellow)  morphExtent: 300@220).
	

	contentArea _ RectangleLikeMorph  new color: Color white.
	
	pages do: [:each | contentArea addMorph: each. 
						each hide].
	
	^contentArea
	! !

!LayoutDemo5 methodsFor: 'page display' stamp: 'hjh 1/12/2013 12:36'!
nextPage
	self hideCurrentPage.
	currentPage := currentPage + 1.
	self displayPage: currentPage! !

!LayoutDemo5 methodsFor: 'page display' stamp: 'hjh 1/12/2013 12:36'!
showPage: aNumber.
	self hideCurrentPage.
	currentPage := aNumber.
	self displayPage: currentPage! !

!LayoutDemo5 methodsFor: 'initialization' stamp: 'hjh 1/12/2013 11:57'!
titleString

	^self class name ! !

!LayoutDemo5b methodsFor: 'GUI building' stamp: 'hjh 1/16/2013 14:12'!
buildMorphicWindow


  self layoutMorph addMorph: self createButtonBar fixedHeight: 40.
  self layoutMorph addMorphUseAll: (contentArea := self makePages).
  self setLabel: self className.
  self openInWorld.

  currentPage := 1.

  self displayPage: currentPage.! !

!LayoutDemo5b methodsFor: 'GUI building' stamp: 'hjh 1/12/2013 12:37'!
createButtonBar


^ LayoutMorph newRow 
	
addMorph: (PluggableButtonMorph 
			model: [ self showPage: 1] action: #value label: 'red') 
	            fixedWidth: 70;
	
addMorph: (PluggableButtonMorph 
			model: [ self showPage: 2] action: #value label: 'green') 
	           fixedWidth: 70;
	
addMorph: (PluggableButtonMorph 
			model: [ self showPage: 3] action: #value label: 'blue') 
	           fixedWidth: 70;

addMorph: (PluggableButtonMorph 
			model: [ self showPage: 4] action: #value label: 'yellow') 
	           fixedWidth: 70! !

!LayoutDemo5b methodsFor: 'page display' stamp: 'hjh 1/16/2013 14:13'!
displayPage: pageNumber
	| page |
	"self adjustButtonsForPage: pageNumber."
	page := pages at: pageNumber.
	contentArea addMorphUseAll: page.
	contentArea layoutSubmorphs! !

!LayoutDemo5b methodsFor: 'page display' stamp: 'hjh 1/16/2013 14:14'!
hideCurrentPage
	| page |
	page := pages at: currentPage.
      contentArea removeMorph: page.
! !

!LayoutDemo5b methodsFor: 'initialization' stamp: 'hjh 1/31/2013 06:40'!
initialExtent
	
	
	^ 480 @ 360! !

!LayoutDemo5b methodsFor: 'initialization' stamp: 'hjh 1/12/2013 18:21'!
initialize

	super initialize.
	
	self buildMorphicWindow.! !

!LayoutDemo5b methodsFor: 'GUI building' stamp: 'hjh 1/12/2013 11:21'!
initializeLabelArea
	"Initialize the label area (titlebar) for the window.
	This is a shorter version of inherited #initializeLabelArea.
	We do not create the other controls"

	|  box |

	box _ self createCloseBox.
	self addMorph: box.
	box morphPosition: 2@2.
	box morphExtent: self boxExtent.

! !

!LayoutDemo5b methodsFor: 'page creation' stamp: 'hjh 1/16/2013 14:15'!
makePages
	| r |
	pages := OrderedCollection new.
	
	pages add: (RectangleLikeMorph new color: Color red; morphWidth: 400; morphHeight: 300).
	pages add: (RectangleLikeMorph new color: Color green; morphWidth: 400; morphHeight: 300).
	pages add: (RectangleLikeMorph new color: Color blue; morphWidth: 400; morphHeight: 300).
	pages add: (RectangleLikeMorph new color: Color yellow; morphWidth: 400; morphHeight: 300).
	
	
	r _ LayoutMorph  newRow color: Color gray; morphWidth: 180; morphHeight: 100.
	r addMorph: (pages at: 1).
	
	^r
	! !

!LayoutDemo5b methodsFor: 'page display' stamp: 'hjh 1/12/2013 12:36'!
nextPage
	self hideCurrentPage.
	currentPage := currentPage + 1.
	self displayPage: currentPage! !

!LayoutDemo5b methodsFor: 'page display' stamp: 'hjh 1/12/2013 12:36'!
showPage: aNumber.
	self hideCurrentPage.
	currentPage := aNumber.
	self displayPage: currentPage! !

!LayoutDemo5b methodsFor: 'initialization' stamp: 'hjh 1/12/2013 11:57'!
titleString

	^self class name ! !

!LayoutDemo5c methodsFor: 'GUI building' stamp: 'hjh 1/16/2013 14:12'!
buildMorphicWindow


  self layoutMorph addMorph: self createButtonBar fixedHeight: 40.
  self layoutMorph addMorphUseAll: (contentArea := self makePages).
  self setLabel: self className.
  self openInWorld.

  currentPage := 1.

  self displayPage: currentPage.! !

!LayoutDemo5c methodsFor: 'GUI building' stamp: 'hjh 1/12/2013 12:37'!
createButtonBar


^ LayoutMorph newRow 
	
addMorph: (PluggableButtonMorph 
			model: [ self showPage: 1] action: #value label: 'red') 
	            fixedWidth: 70;
	
addMorph: (PluggableButtonMorph 
			model: [ self showPage: 2] action: #value label: 'green') 
	           fixedWidth: 70;
	
addMorph: (PluggableButtonMorph 
			model: [ self showPage: 3] action: #value label: 'blue') 
	           fixedWidth: 70;

addMorph: (PluggableButtonMorph 
			model: [ self showPage: 4] action: #value label: 'yellow') 
	           fixedWidth: 70! !

!LayoutDemo5c methodsFor: 'page display' stamp: 'hjh 1/16/2013 14:13'!
displayPage: pageNumber
	| page |
	"self adjustButtonsForPage: pageNumber."
	page := pages at: pageNumber.
	contentArea addMorphUseAll: page.
	contentArea layoutSubmorphs! !

!LayoutDemo5c methodsFor: 'page display' stamp: 'hjh 1/16/2013 14:14'!
hideCurrentPage
	| page |
	page := pages at: currentPage.
      contentArea removeMorph: page.
! !

!LayoutDemo5c methodsFor: 'initialization' stamp: 'hjh 1/31/2013 06:40'!
initialExtent
	
	
	^ 480 @ 360! !

!LayoutDemo5c methodsFor: 'initialization' stamp: 'hjh 1/16/2013 14:24'!
initialize
	super initialize.

	self buildMorphicWindow.! !

!LayoutDemo5c methodsFor: 'GUI building' stamp: 'hjh 1/12/2013 11:21'!
initializeLabelArea
	"Initialize the label area (titlebar) for the window.
	This is a shorter version of inherited #initializeLabelArea.
	We do not create the other controls"

	|  box |

	box _ self createCloseBox.
	self addMorph: box.
	box morphPosition: 2@2.
	box morphExtent: self boxExtent.

! !

!LayoutDemo5c methodsFor: 'page creation' stamp: 'hjh 2/10/2013 16:40'!
makePages
	| r page1 page2 page3 |
	pages := OrderedCollection new.
	
	pages add: (page1 _ DragAndDropAreaMorph new color: Color red).
	pages add: (page2 _ DragAndDropAreaMorph new color: Color green).
	pages add: (page3 _ DragAndDropAreaMorph new color: Color blue).
	pages add: (RectangleLikeMorph new color: Color yellow).
	
	page1 addMorph: (EllipseMorph new morphPosition: 40@60; morphWidth: 100; morphHeight:100;
						color: Color white).
      page2 addMorph: ((LimitedHeightTextMorph new
						maxHeight: 48;
						model: (TextModel new contents: 'abc def ghi jkl mno pqr stu vwx yz'))
						morphPosition: 40@60).
								
	page3 addMorph: (EllipseMorph new morphPosition: 89@20; morphWidth: 50; morphHeight:50).
.

	
	r _ LayoutMorph  newRow color: Color gray; morphWidth: 180; morphHeight: 100.
	r addMorphUseAll: (pages at: 1).
	
	^r
	! !

!LayoutDemo5c methodsFor: 'page display' stamp: 'hjh 1/12/2013 12:36'!
nextPage
	self hideCurrentPage.
	currentPage := currentPage + 1.
	self displayPage: currentPage! !

!LayoutDemo5c methodsFor: 'page display' stamp: 'hjh 1/12/2013 12:36'!
showPage: aNumber.
	self hideCurrentPage.
	currentPage := aNumber.
	self displayPage: currentPage! !

!LayoutDemo5c methodsFor: 'initialization' stamp: 'hjh 1/12/2013 11:57'!
titleString

	^self class name ! !

!LayoutDemo5d methodsFor: 'GUI building' stamp: 'hjh 1/16/2013 14:12'!
buildMorphicWindow


  self layoutMorph addMorph: self createButtonBar fixedHeight: 40.
  self layoutMorph addMorphUseAll: (contentArea := self makePages).
  self setLabel: self className.
  self openInWorld.

  currentPage := 1.

  self displayPage: currentPage.! !

!LayoutDemo5d methodsFor: 'GUI building' stamp: 'hjh 1/12/2013 12:37'!
createButtonBar


^ LayoutMorph newRow 
	
addMorph: (PluggableButtonMorph 
			model: [ self showPage: 1] action: #value label: 'red') 
	            fixedWidth: 70;
	
addMorph: (PluggableButtonMorph 
			model: [ self showPage: 2] action: #value label: 'green') 
	           fixedWidth: 70;
	
addMorph: (PluggableButtonMorph 
			model: [ self showPage: 3] action: #value label: 'blue') 
	           fixedWidth: 70;

addMorph: (PluggableButtonMorph 
			model: [ self showPage: 4] action: #value label: 'yellow') 
	           fixedWidth: 70! !

!LayoutDemo5d methodsFor: 'page creation' stamp: 'hjh 2/10/2013 16:40'!
createPage1


| page1 |

								

page1 _ DragAndDropAreaMorph new color: Color red.

page1 addMorph: (EllipseMorph new morphPosition: 40@60; morphWidth: 100; morphHeight:100;
						color: Color white).
     
^page1! !

!LayoutDemo5d methodsFor: 'page creation' stamp: 'hjh 2/10/2013 16:41'!
createPage2


| page2 |

								

page2 _ DragAndDropAreaMorph new color: Color green.

page2 addMorph: ((LimitedHeightTextMorph new
						maxHeight: 48;
						model: (TextModel new contents: 'abc def ghi jkl mno pqr stu vwx yz'))
						morphPosition: 40@60).

^page2! !

!LayoutDemo5d methodsFor: 'page creation' stamp: 'hjh 2/10/2013 16:41'!
createPage3


| page3 |

page3 _ DragAndDropAreaMorph new color: Color blue.

page3 addMorph: (EllipseMorph new morphPosition: 89@20; morphWidth: 50; morphHeight:50).

^page3! !

!LayoutDemo5d methodsFor: 'page display' stamp: 'hjh 1/16/2013 14:13'!
displayPage: pageNumber
	| page |
	"self adjustButtonsForPage: pageNumber."
	page := pages at: pageNumber.
	contentArea addMorphUseAll: page.
	contentArea layoutSubmorphs! !

!LayoutDemo5d methodsFor: 'page display' stamp: 'hjh 1/16/2013 14:14'!
hideCurrentPage
	| page |
	page := pages at: currentPage.
      contentArea removeMorph: page.
! !

!LayoutDemo5d methodsFor: 'initialization' stamp: 'hjh 1/31/2013 06:40'!
initialExtent
	
	
	^ 480 @ 360! !

!LayoutDemo5d methodsFor: 'initialization' stamp: 'hjh 1/16/2013 14:24'!
initialize
	super initialize.

	self buildMorphicWindow.! !

!LayoutDemo5d methodsFor: 'GUI building' stamp: 'hjh 1/12/2013 11:21'!
initializeLabelArea
	"Initialize the label area (titlebar) for the window.
	This is a shorter version of inherited #initializeLabelArea.
	We do not create the other controls"

	|  box |

	box _ self createCloseBox.
	self addMorph: box.
	box morphPosition: 2@2.
	box morphExtent: self boxExtent.

! !

!LayoutDemo5d methodsFor: 'page creation' stamp: 'hjh 1/16/2013 15:12'!
makePages
	| p  |
	pages := OrderedCollection new.
	
	pages add: self createPage1.
	pages add: self createPage2.
	pages add: self createPage3.
	pages add: (RectangleLikeMorph new color: Color yellow).
	
	
	p _ LayoutMorph  newRow color: Color gray; morphWidth: 180; morphHeight: 100.
	p addMorphUseAll: (pages at: 1).
	
	^p
	! !

!LayoutDemo5d methodsFor: 'page display' stamp: 'hjh 1/12/2013 12:36'!
nextPage
	self hideCurrentPage.
	currentPage := currentPage + 1.
	self displayPage: currentPage! !

!LayoutDemo5d methodsFor: 'page display' stamp: 'hjh 1/12/2013 12:36'!
showPage: aNumber.
	self hideCurrentPage.
	currentPage := aNumber.
	self displayPage: currentPage! !

!LayoutDemo5d methodsFor: 'initialization' stamp: 'hjh 1/12/2013 11:57'!
titleString

	^self class name ! !

!LayoutDemo5e methodsFor: 'GUI building' stamp: 'hjh 1/16/2013 14:12'!
buildMorphicWindow


  self layoutMorph addMorph: self createButtonBar fixedHeight: 40.
  self layoutMorph addMorphUseAll: (contentArea := self makePages).
  self setLabel: self className.
  self openInWorld.

  currentPage := 1.

  self displayPage: currentPage.! !

!LayoutDemo5e methodsFor: 'GUI building' stamp: 'hjh 1/12/2013 12:37'!
createButtonBar


^ LayoutMorph newRow 
	
addMorph: (PluggableButtonMorph 
			model: [ self showPage: 1] action: #value label: 'red') 
	            fixedWidth: 70;
	
addMorph: (PluggableButtonMorph 
			model: [ self showPage: 2] action: #value label: 'green') 
	           fixedWidth: 70;
	
addMorph: (PluggableButtonMorph 
			model: [ self showPage: 3] action: #value label: 'blue') 
	           fixedWidth: 70;

addMorph: (PluggableButtonMorph 
			model: [ self showPage: 4] action: #value label: 'yellow') 
	           fixedWidth: 70! !

!LayoutDemo5e methodsFor: 'page creation' stamp: 'hjh 1/29/2013 16:16'!
createPage1


| page1 |

								

page1 _ DragAndDropAreaMorph new color: Color red.

page1 addMorph: (EllipseMorph new morphPosition: 40@60; morphWidth: 100; morphHeight:100;
						color: Color white).
     
^page1! !

!LayoutDemo5e methodsFor: 'page creation' stamp: 'hjh 1/29/2013 16:16'!
createPage2


| page2 |

								

page2 _ DragAndDropAreaMorph new color: Color green.

page2 addMorph: ((LimitedHeightTextMorph new
						maxHeight: 48;
						model: (TextModel new contents: 'abc def ghi jkl mno pqr stu vwx yz'))
						morphPosition: 40@60).

^page2! !

!LayoutDemo5e methodsFor: 'page creation' stamp: 'hjh 1/16/2013 15:36'!
createPage3

| page3 col |

page3 _ LayoutMorph newRow color: Color gray; morphWidth: 400; morphHeight:300.

10 timesRepeat: [

    col _ LayoutMorph  newColumn color: Color blue.

    col addMorphUseAll: (EllipseMorph new morphWidth: 50; morphHeight:60).
    col addMorphUseAll: (EllipseMorph new color: Color random; morphWidth: 50; morphHeight:60).
    col addMorphUseAll: (EllipseMorph new color: Color tan; morphWidth: 50; morphHeight:60).
    col addMorphUseAll: (EllipseMorph new color: Color random; morphWidth: 50; morphHeight:60).
    col addMorphUseAll: (EllipseMorph new color: Color brown; morphWidth: 50; morphHeight:60).
   
 page3 addMorphUseAll: col.
].

^page3! !

!LayoutDemo5e methodsFor: 'page display' stamp: 'hjh 1/16/2013 14:13'!
displayPage: pageNumber
	| page |
	"self adjustButtonsForPage: pageNumber."
	page := pages at: pageNumber.
	contentArea addMorphUseAll: page.
	contentArea layoutSubmorphs! !

!LayoutDemo5e methodsFor: 'page display' stamp: 'hjh 1/16/2013 14:14'!
hideCurrentPage
	| page |
	page := pages at: currentPage.
      contentArea removeMorph: page.
! !

!LayoutDemo5e methodsFor: 'initialization' stamp: 'hjh 1/31/2013 06:41'!
initialExtent
	
	
	^ 480 @ 360! !

!LayoutDemo5e methodsFor: 'initialization' stamp: 'hjh 1/16/2013 14:24'!
initialize
	super initialize.

	self buildMorphicWindow.! !

!LayoutDemo5e methodsFor: 'GUI building' stamp: 'hjh 1/12/2013 11:21'!
initializeLabelArea
	"Initialize the label area (titlebar) for the window.
	This is a shorter version of inherited #initializeLabelArea.
	We do not create the other controls"

	|  box |

	box _ self createCloseBox.
	self addMorph: box.
	box morphPosition: 2@2.
	box morphExtent: self boxExtent.

! !

!LayoutDemo5e methodsFor: 'page creation' stamp: 'hjh 1/29/2013 16:16'!
makePages
	| p  |
	pages := OrderedCollection new.
	
	pages add: self createPage1.
	pages add: self createPage2.
	pages add: self createPage3.
	pages add: (DragAndDropAreaMorph new color: Color yellow).
	
	
	p _ LayoutMorph  newRow color: Color gray; morphWidth: 180; morphHeight: 100.
	p addMorphUseAll: (pages at: 1).
	
	^p
	! !

!LayoutDemo5e methodsFor: 'page display' stamp: 'hjh 1/12/2013 12:36'!
nextPage
	self hideCurrentPage.
	currentPage := currentPage + 1.
	self displayPage: currentPage! !

!LayoutDemo5e methodsFor: 'page display' stamp: 'hjh 1/12/2013 12:36'!
showPage: aNumber.
	self hideCurrentPage.
	currentPage := aNumber.
	self displayPage: currentPage! !

!LayoutDemo5e methodsFor: 'initialization' stamp: 'hjh 1/12/2013 11:57'!
titleString

	^self class name ! !

!LayoutDemo5f methodsFor: 'GUI building' stamp: 'hjh 1/29/2013 18:10'!
buildMorphicWindow


  self layoutMorph addMorph: self createButtonBar fixedHeight: 40.
  self layoutMorph addMorphUseAll: (contentArea := self makePages).
  self setLabel: self titleString.
  self openInWorld.

  currentPage := 1.

  self displayPage: currentPage.! !

!LayoutDemo5f methodsFor: 'GUI building' stamp: 'hjh 1/12/2013 12:37'!
createButtonBar


^ LayoutMorph newRow 
	
addMorph: (PluggableButtonMorph 
			model: [ self showPage: 1] action: #value label: 'red') 
	            fixedWidth: 70;
	
addMorph: (PluggableButtonMorph 
			model: [ self showPage: 2] action: #value label: 'green') 
	           fixedWidth: 70;
	
addMorph: (PluggableButtonMorph 
			model: [ self showPage: 3] action: #value label: 'blue') 
	           fixedWidth: 70;

addMorph: (PluggableButtonMorph 
			model: [ self showPage: 4] action: #value label: 'yellow') 
	           fixedWidth: 70! !

!LayoutDemo5f methodsFor: 'page creation' stamp: 'hjh 1/29/2013 16:16'!
createPage1


| page1 |

								

page1 _ DragAndDropAreaMorph new color: Color red.

page1 addMorph: (EllipseMorph new morphPosition: 40@60; morphWidth: 100; morphHeight:100;
						color: Color white).
     
^page1! !

!LayoutDemo5f methodsFor: 'page creation' stamp: 'hjh 1/29/2013 16:16'!
createPage2


| page2 |

								

page2 _ DragAndDropAreaMorph new color: Color green.

page2 addMorph: ((LimitedHeightTextMorph new
						maxHeight: 48;
						model: (TextModel new contents: 'abc def ghi jkl mno pqr stu vwx yz'))
						morphPosition: 40@60).

^page2! !

!LayoutDemo5f methodsFor: 'page creation' stamp: 'hjh 1/29/2013 17:00'!
createPage3

| page3 |

page3 _ LayoutMorph newRow color: Color gray; morphWidth: 400; morphHeight:300.

25 timesRepeat: [page3 addMorphUseAll: (RectangleLikeMorph new color: Color red lighter)].
5 timesRepeat: [page3 addMorphUseAll: (RectangleLikeMorph new color: Color random)].





^page3! !

!LayoutDemo5f methodsFor: 'page display' stamp: 'hjh 1/16/2013 14:13'!
displayPage: pageNumber
	| page |
	"self adjustButtonsForPage: pageNumber."
	page := pages at: pageNumber.
	contentArea addMorphUseAll: page.
	contentArea layoutSubmorphs! !

!LayoutDemo5f methodsFor: 'page display' stamp: 'hjh 1/16/2013 14:14'!
hideCurrentPage
	| page |
	page := pages at: currentPage.
      contentArea removeMorph: page.
! !

!LayoutDemo5f methodsFor: 'initialization' stamp: 'hjh 1/31/2013 06:41'!
initialExtent
	
	
	^ 480 @ 360! !

!LayoutDemo5f methodsFor: 'initialization' stamp: 'hjh 1/16/2013 14:24'!
initialize
	super initialize.

	self buildMorphicWindow.! !

!LayoutDemo5f methodsFor: 'GUI building' stamp: 'hjh 1/12/2013 11:21'!
initializeLabelArea
	"Initialize the label area (titlebar) for the window.
	This is a shorter version of inherited #initializeLabelArea.
	We do not create the other controls"

	|  box |

	box _ self createCloseBox.
	self addMorph: box.
	box morphPosition: 2@2.
	box morphExtent: self boxExtent.

! !

!LayoutDemo5f methodsFor: 'page creation' stamp: 'hjh 1/29/2013 16:16'!
makePages
	| p  |
	pages := OrderedCollection new.
	
	pages add: self createPage1.
	pages add: self createPage2.
	pages add: self createPage3.
	pages add: (DragAndDropAreaMorph new color: Color yellow).
	
	
	p _ LayoutMorph  newRow color: Color gray; morphWidth: 180; morphHeight: 100.
	p addMorphUseAll: (pages at: 1).
	
	^p
	! !

!LayoutDemo5f methodsFor: 'page display' stamp: 'hjh 1/12/2013 12:36'!
nextPage
	self hideCurrentPage.
	currentPage := currentPage + 1.
	self displayPage: currentPage! !

!LayoutDemo5f methodsFor: 'page display' stamp: 'hjh 1/12/2013 12:36'!
showPage: aNumber.
	self hideCurrentPage.
	currentPage := aNumber.
	self displayPage: currentPage! !

!LayoutDemo5f methodsFor: 'initialization' stamp: 'hjh 1/12/2013 11:57'!
titleString

	^self class name ! !

!LayoutDemo6 methodsFor: 'pages' stamp: 'hjh 2/10/2013 17:20'!
addPageTo: contentArea name: aName

	| colorSymbol |
	
	colorSymbol := aName asSymbol.

      contentArea addMorph: (DragAndDropAreaMorph new 
								color: (Color perform: colorSymbol);
								setProperty: #name toValue: colorSymbol;
								morphExtent: 430@250
							).
								
	
	
	


    ! !

!LayoutDemo6 methodsFor: 'pages' stamp: 'hjh 1/31/2013 05:20'!
bringPageToFront: aPageName

 	| page |
	
	page := contentArea submorphs detect: [ :morph | (morph valueOfProperty: #name) = aPageName].
	
	contentArea addMorphFront: page. 
	


! !

!LayoutDemo6 methodsFor: 'GUI building' stamp: 'hjh 2/10/2013 18:25'!
buildMorphicWindow

self setLabel: self titleString.


self layoutMorph addMorph:  self createButtonBar fixedHeight: 40.
self layoutMorph addMorphUseAll: self makeContentArea.

self openInWorld
! !

!LayoutDemo6 methodsFor: 'GUI building' stamp: 'hjh 1/31/2013 05:17'!
createButtonBar


^ LayoutMorph newRow 
	
addMorph: (PluggableButtonMorph 
			model: [ self bringPageToFront: #red] action: #value label: 'red') 
	            fixedWidth: 70;
	
addMorph: (PluggableButtonMorph 
			model: [ self  bringPageToFront: #green] action: #value label: 'green') 
	           fixedWidth: 70;
	
addMorph: (PluggableButtonMorph 
			model: [ self bringPageToFront: #blue] action: #value label: 'blue') 
	           fixedWidth: 70;

addMorph: (PluggableButtonMorph 
			model: [ self bringPageToFront: #yellow] action: #value label: 'yellow') 
	           fixedWidth: 70! !

!LayoutDemo6 methodsFor: 'initialization' stamp: 'hjh 1/31/2013 06:33'!
initialExtent
	
	
	^ 480 @ 360! !

!LayoutDemo6 methodsFor: 'initialization' stamp: 'hjh 1/12/2013 11:18'!
initialize

	super initialize.
	self buildMorphicWindow.! !

!LayoutDemo6 methodsFor: 'GUI building' stamp: 'hjh 1/12/2013 11:21'!
initializeLabelArea
	"Initialize the label area (titlebar) for the window.
	This is a shorter version of inherited #initializeLabelArea.
	We do not create the other controls"

	|  box |

	box _ self createCloseBox.
	self addMorph: box.
	box morphPosition: 2@2.
	box morphExtent: self boxExtent.

! !

!LayoutDemo6 methodsFor: 'pages' stamp: 'hjh 2/10/2013 17:14'!
makeContentArea

 	contentArea := RectangleLikeMorph new color: Color gray.  "This morph does not do layout control"

	"morphs are added on top of each other"

      self addPageTo: contentArea name: 'red'.
      self addPageTo: contentArea name: 'green'.
      self addPageTo: contentArea name: 'blue'.
      self addPageTo: contentArea name: 'yellow'.
								
	
	^ contentArea


    ! !

!LayoutDemo6 methodsFor: 'initialization' stamp: 'hjh 2/10/2013 18:25'!
titleString

	^self class name ! !

!LayoutDemo6 class methodsFor: 'as yet unclassified' stamp: 'hjh 2/10/2013 19:13'!
open

	^self new openInWorld! !

!LayoutDemo6b methodsFor: 'pages' stamp: 'hjh 2/10/2013 17:31'!
addPageTo: contentArea name: aName

	| colorSymbol b |
	
	colorSymbol := aName asSymbol.

	b := BorderedRectMorph new 
											color: (Color perform: colorSymbol) darker;
											morphExtent: 100@100.

      contentArea addMorph: (LayoutMorph newColumn 
								color: (Color perform: colorSymbol);
								setProperty: #name toValue: colorSymbol;
								addMorph: b;
								morphExtent: 430@250
							).
								
								
	


    ! !

!LayoutDemo6b methodsFor: 'pages' stamp: 'hjh 1/31/2013 05:20'!
bringPageToFront: aPageName

 	| page |
	
	page := contentArea submorphs detect: [ :morph | (morph valueOfProperty: #name) = aPageName].
	
	contentArea addMorphFront: page. 
	


! !

!LayoutDemo6b methodsFor: 'GUI building' stamp: 'hjh 2/10/2013 18:25'!
buildMorphicWindow

self setLabel: self titleString.


self layoutMorph addMorph:  self createButtonBar fixedHeight: 40.
self layoutMorph addMorphUseAll: self makeContentArea.

self openInWorld
! !

!LayoutDemo6b methodsFor: 'GUI building' stamp: 'hjh 1/31/2013 05:17'!
createButtonBar


^ LayoutMorph newRow 
	
addMorph: (PluggableButtonMorph 
			model: [ self bringPageToFront: #red] action: #value label: 'red') 
	            fixedWidth: 70;
	
addMorph: (PluggableButtonMorph 
			model: [ self  bringPageToFront: #green] action: #value label: 'green') 
	           fixedWidth: 70;
	
addMorph: (PluggableButtonMorph 
			model: [ self bringPageToFront: #blue] action: #value label: 'blue') 
	           fixedWidth: 70;

addMorph: (PluggableButtonMorph 
			model: [ self bringPageToFront: #yellow] action: #value label: 'yellow') 
	           fixedWidth: 70! !

!LayoutDemo6b methodsFor: 'initialization' stamp: 'hjh 1/31/2013 06:33'!
initialExtent
	
	
	^ 480 @ 360! !

!LayoutDemo6b methodsFor: 'initialization' stamp: 'hjh 1/12/2013 11:18'!
initialize

	super initialize.
	self buildMorphicWindow.! !

!LayoutDemo6b methodsFor: 'GUI building' stamp: 'hjh 1/12/2013 11:21'!
initializeLabelArea
	"Initialize the label area (titlebar) for the window.
	This is a shorter version of inherited #initializeLabelArea.
	We do not create the other controls"

	|  box |

	box _ self createCloseBox.
	self addMorph: box.
	box morphPosition: 2@2.
	box morphExtent: self boxExtent.

! !

!LayoutDemo6b methodsFor: 'pages' stamp: 'hjh 2/10/2013 17:14'!
makeContentArea

 	contentArea := RectangleLikeMorph new color: Color gray.  "This morph does not do layout control"

	"morphs are added on top of each other"

      self addPageTo: contentArea name: 'red'.
      self addPageTo: contentArea name: 'green'.
      self addPageTo: contentArea name: 'blue'.
      self addPageTo: contentArea name: 'yellow'.
								
	
	^ contentArea


    ! !

!LayoutDemo6b methodsFor: 'initialization' stamp: 'hjh 2/10/2013 18:25'!
titleString

	^self class name ! !

!LayoutDemo6b class methodsFor: 'as yet unclassified' stamp: 'hjh 2/10/2013 19:13'!
open

	^self new openInWorld! !

!LayoutDemo6c methodsFor: 'pages' stamp: 'hjh 2/10/2013 18:10'!
addPageTo: contentArea name: aName

	| colorSymbol b |
	
	colorSymbol := aName asSymbol.

	b := ImageMorph new image: (ABC at: aName).

      contentArea addMorph: (LayoutMorph newColumn 
								setProperty: #name toValue: colorSymbol;
								addMorph: b;
								morphExtent: 500@350
							).
								
								
	


    ! !

!LayoutDemo6c methodsFor: 'pages' stamp: 'hjh 1/31/2013 05:20'!
bringPageToFront: aPageName

 	| page |
	
	page := contentArea submorphs detect: [ :morph | (morph valueOfProperty: #name) = aPageName].
	
	contentArea addMorphFront: page. 
	


! !

!LayoutDemo6c methodsFor: 'GUI building' stamp: 'hjh 2/10/2013 18:26'!
buildMorphicWindow

self setLabel: self titleString.

self layoutMorph addMorph:  self createButtonBar fixedHeight: 40.
self layoutMorph addMorphUseAll: self makeContentArea.

self openInWorld
! !

!LayoutDemo6c methodsFor: 'GUI building' stamp: 'hjh 2/10/2013 17:38'!
createButtonBar


^ LayoutMorph newRow 
	
addMorph: (PluggableButtonMorph 
			model: [ self bringPageToFront: #Apple] action: #value label: 'Apple') 
	            fixedWidth: 70;
	
addMorph: (PluggableButtonMorph 
			model: [ self  bringPageToFront: #Ball] action: #value label: 'Ball') 
	           fixedWidth: 70;
	
addMorph: (PluggableButtonMorph 
			model: [ self bringPageToFront: #Cat] action: #value label: 'Cat') 
	           fixedWidth: 70;

addMorph: (PluggableButtonMorph 
			model: [ self bringPageToFront: #Duck] action: #value label: 'Duck') 
	           fixedWidth: 70! !

!LayoutDemo6c methodsFor: 'initialization' stamp: 'hjh 2/10/2013 17:43'!
initialExtent
	
	
	^ 600 @ 480! !

!LayoutDemo6c methodsFor: 'initialization' stamp: 'hjh 1/12/2013 11:18'!
initialize

	super initialize.
	self buildMorphicWindow.! !

!LayoutDemo6c methodsFor: 'GUI building' stamp: 'hjh 1/12/2013 11:21'!
initializeLabelArea
	"Initialize the label area (titlebar) for the window.
	This is a shorter version of inherited #initializeLabelArea.
	We do not create the other controls"

	|  box |

	box _ self createCloseBox.
	self addMorph: box.
	box morphPosition: 2@2.
	box morphExtent: self boxExtent.

! !

!LayoutDemo6c methodsFor: 'pages' stamp: 'hjh 2/10/2013 17:39'!
makeContentArea

 	contentArea := RectangleLikeMorph new color: Color gray.  "This morph does not do layout control"

	"morphs are added on top of each other"

      self addPageTo: contentArea name: 'Apple'.
      self addPageTo: contentArea name: 'Ball'.
      self addPageTo: contentArea name: 'Cat'.
      self addPageTo: contentArea name: 'Duck'.
								
	
	^ contentArea


    ! !

!LayoutDemo6c methodsFor: 'initialization' stamp: 'hjh 2/10/2013 18:26'!
titleString

	^self class name ! !

!LayoutDemo6c class methodsFor: 'as yet unclassified' stamp: 'hjh 2/10/2013 19:13'!
open

	^self new openInWorld! !

!LayoutDemo6dABC methodsFor: 'GUI building' stamp: 'hjh 2/10/2013 18:17'!
addButtonTo: aMorph name: aName
| aSymbol |


aSymbol := aName asSymbol.

aMorph addMorph: (PluggableButtonMorph 
			model: [ self bringPageToFront: aSymbol] action: #value label: aName) 
	            fixedWidth: 70! !

!LayoutDemo6dABC methodsFor: 'pages' stamp: 'hjh 2/11/2013 09:41'!
addPageTo: contentArea name: aName

	|  b aSymbol |
	
	aSymbol := aName asSymbol.

	b := ImageMorph new image: 
		((Smalltalk at: #ContentPack2ABC) current  at: aName).

      contentArea addMorph: (LayoutMorph newColumn 
								setProperty: #name toValue: aSymbol;
								color:  self class defaultBackgroundColor;
								addMorph: b;
								morphExtent: 500@350
							).
								! !

!LayoutDemo6dABC methodsFor: 'pages' stamp: 'hjh 1/31/2013 05:20'!
bringPageToFront: aPageName

 	| page |
	
	page := contentArea submorphs detect: [ :morph | (morph valueOfProperty: #name) = aPageName].
	
	contentArea addMorphFront: page. 
	


! !

!LayoutDemo6dABC methodsFor: 'GUI building' stamp: 'hjh 2/10/2013 18:54'!
buildMorphicWindow

self setLabel: self titleString.


self layoutMorph addMorph:  self createButtonBar fixedHeight: 40.
self layoutMorph addMorph:  self createButtonBar2 fixedHeight: 40.
self layoutMorph addMorph:  self createButtonBar3 fixedHeight: 40.
self layoutMorph addMorph:  self createButtonBar4 fixedHeight: 40.
self layoutMorph addMorph:  self createButtonBar5 fixedHeight: 40.


self layoutMorph addMorphUseAll: self makeContentArea.

self bringPageToFront: #Apple.

self openInWorld.

! !

!LayoutDemo6dABC methodsFor: 'GUI building' stamp: 'hjh 2/10/2013 18:27'!
createButtonBar
 | bar |

	bar := LayoutMorph newRow. 

 	self addButtonTo: bar  name: 'Apple'. 
	self addButtonTo: bar  name: 'Ball'. 
 	self addButtonTo: bar  name: 'Cat'. 
 	self addButtonTo: bar  name: 'Duck'. 
 	self addButtonTo: bar  name: 'Elephant'. 
 	
	
	^bar
	
! !

!LayoutDemo6dABC methodsFor: 'GUI building' stamp: 'hjh 2/10/2013 18:29'!
createButtonBar2
 | bar |

	bar := LayoutMorph newRow. 

 	self addButtonTo: bar  name: 'Fish'. 
 	self addButtonTo: bar  name: 'Gate'. 
	self addButtonTo: bar  name: 'Horse'. 
	self addButtonTo: bar  name: 'Igloo'. 
	self addButtonTo: bar  name: 'Jam'. 
 	
	
	^bar
	
! !

!LayoutDemo6dABC methodsFor: 'GUI building' stamp: 'hjh 2/10/2013 18:33'!
createButtonBar3
 | bar |

	bar := LayoutMorph newRow. 

 	self addButtonTo: bar  name: 'Kangaroo'. 
 	self addButtonTo: bar  name: 'Lion'. 
	self addButtonTo: bar  name: 'Mouse'. 
	self addButtonTo: bar  name: 'Nest'. 
	self addButtonTo: bar  name: 'Octopus'. 
 	
	
	^bar
	
! !

!LayoutDemo6dABC methodsFor: 'GUI building' stamp: 'hjh 2/10/2013 18:50'!
createButtonBar4
 | bar |

	bar := LayoutMorph newRow. 

 	self addButtonTo: bar  name: 'Pig'. 
 	self addButtonTo: bar  name: 'Queen'. 
	self addButtonTo: bar  name: 'Road'. 
	self addButtonTo: bar  name: 'Sun'. 
	self addButtonTo: bar  name: 'Turtle'. 
	
	
	^bar
	
! !

!LayoutDemo6dABC methodsFor: 'GUI building' stamp: 'hjh 2/10/2013 18:54'!
createButtonBar5
 | bar |

	bar := LayoutMorph newRow. 

 	self addButtonTo: bar  name: 'Umbrella'. 
 	self addButtonTo: bar  name: 'Volcano'. 
	self addButtonTo: bar  name: 'Window'. 
	self addButtonTo: bar  name: 'Xylophon'. 
	self addButtonTo: bar  name: 'Yo-yo'. 
	self addButtonTo: bar  name: 'Zebra'. 
	
	^bar
	
! !

!LayoutDemo6dABC methodsFor: 'initialization' stamp: 'hjh 2/10/2013 18:55'!
initialExtent
	
	
	^ 500 @ 600! !

!LayoutDemo6dABC methodsFor: 'initialization' stamp: 'hjh 1/12/2013 11:18'!
initialize

	super initialize.
	self buildMorphicWindow.! !

!LayoutDemo6dABC methodsFor: 'GUI building' stamp: 'hjh 1/12/2013 11:21'!
initializeLabelArea
	"Initialize the label area (titlebar) for the window.
	This is a shorter version of inherited #initializeLabelArea.
	We do not create the other controls"

	|  box |

	box _ self createCloseBox.
	self addMorph: box.
	box morphPosition: 2@2.
	box morphExtent: self boxExtent.

! !

!LayoutDemo6dABC methodsFor: 'pages' stamp: 'hjh 2/10/2013 18:54'!
makeContentArea
	"ABC"
 	contentArea := RectangleLikeMorph new color: Color gray.  "This morph does not do layout control"

	"morphs are added on top of each other"

      self addPageTo: contentArea name: 'Apple'.
      self addPageTo: contentArea name: 'Ball'.
      self addPageTo: contentArea name: 'Cat'.
      self addPageTo: contentArea name: 'Duck'.
	self addPageTo: contentArea name: 'Elephant'.

	self addPageTo: contentArea name: 'Fish'.
	self addPageTo: contentArea name: 'Gate'.							
	self addPageTo: contentArea name: 'Horse'.	
	self addPageTo: contentArea name: 'Igloo'.
	self addPageTo: contentArea name: 'Jam'.	

	self addPageTo: contentArea name: 'Kangaroo'.	
	self addPageTo: contentArea name: 'Lion'.	
	self addPageTo: contentArea name: 'Mouse'.	
	self addPageTo: contentArea name: 'Nest'.	
	self addPageTo: contentArea name: 'Octopus'.	
	
	self addPageTo: contentArea name: 'Pig'.	
	self addPageTo: contentArea name: 'Queen'.	
	self addPageTo: contentArea name: 'Road'.	
	self addPageTo: contentArea name: 'Sun'.	
	self addPageTo: contentArea name: 'Turtle'.	
	
	self addPageTo: contentArea name: 'Pig'.	
	self addPageTo: contentArea name: 'Queen'.	
	self addPageTo: contentArea name: 'Road'.	
	self addPageTo: contentArea name: 'Sun'.	
	self addPageTo: contentArea name: 'Turtle'.	
	
	self addPageTo: contentArea name: 'Umbrella'.	
	self addPageTo: contentArea name: 'Volcano'.	
	self addPageTo: contentArea name: 'Window'.	
	self addPageTo: contentArea name: 'Xylophon'.	
	self addPageTo: contentArea name: 'Yo-yo'.	
	self addPageTo: contentArea name: 'Zebra'.	

	^ contentArea


    ! !

!LayoutDemo6dABC methodsFor: 'initialization' stamp: 'hjh 2/10/2013 18:26'!
titleString

	^'ABC book' ! !

!LayoutDemo6dABC class methodsFor: 'as yet unclassified' stamp: 'hjh 2/11/2013 09:36'!
checkIfABCdictionaryWithPicturesPresent

	(Smalltalk at: #ContentPack2ABC ifAbsent: []) isNil
		ifTrue: [self inform: 'You need to have loaded ''ContentPack2ABC'' from https://github.com/hhzl/ContentPack.' . ^false].
		
	^true	! !

!LayoutDemo6dABC class methodsFor: 'as yet unclassified' stamp: 'hjh 2/11/2013 09:19'!
defaultBackgroundColor

	^Color blue! !

!LayoutDemo6dABC class methodsFor: 'as yet unclassified' stamp: 'hjh 2/11/2013 09:35'!
open

	self checkIfABCdictionaryWithPicturesPresent
	
	    ifTrue:  [^self new openInWorld]! !

!LayoutDemo8Timer methodsFor: 'GUI building' stamp: 'hjh 1/29/2013 19:02'!
buildMorphicWindow


 
  self setLabel: self titleString.
  self layoutMorph beRow.
  25 timesRepeat: [ | circle | circle := (EllipseMorph new color: Color red muchLighter; 
	morphExtent: 20@20).
	minuteMorphs add: circle.
	self layoutMorph addMorph: circle].

  5 timesRepeat: [ | circle | circle := (EllipseMorph new color: Color blue muchLighter; 
	morphExtent: 20@20).
	minuteMorphs add: circle.
	self layoutMorph addMorph: circle].

 ! !

!LayoutDemo8Timer methodsFor: 'GUI building' stamp: 'hjh 1/29/2013 21:53'!
initialExtent
	
	
	^ 610 @ 40! !

!LayoutDemo8Timer methodsFor: 'initialization' stamp: 'hjh 1/29/2013 21:30'!
initialize
	super initialize.
	
	minuteMorphs := OrderedCollection new.
	startTime := Time now.

	self buildMorphicWindow.! !

!LayoutDemo8Timer methodsFor: 'GUI building' stamp: 'hjh 1/29/2013 18:12'!
initializeLabelArea
	"Initialize the label area (titlebar) for the window.
	This is a shorter version of inherited #initializeLabelArea.
	We do not create the other controls"

	|  box |

	box _ self createCloseBox.
	self addMorph: box.
	box morphPosition: 2@2.
	box morphExtent: self boxExtent.

! !

!LayoutDemo8Timer methodsFor: 'updating' stamp: 'hjh 1/29/2013 21:49'!
step
	| currentColor currentMorph minutes |

	
	minutes := (Time now - startTime) minutes.
	minutes > 0 ifTrue: [
				currentMorph := minuteMorphs at:  minutes ifAbsent: [minuteMorphs last].
			
				currentColor := currentMorph color darker.
				minutes <= 25 ifTrue: [currentColor := Color red]. "set to red for the first 25"
				currentMorph color: currentColor
				]! !

!LayoutDemo8Timer methodsFor: 'updating' stamp: 'hjh 1/29/2013 21:50'!
stepTime

	^5000! !

!LayoutDemo8Timer methodsFor: 'initialization' stamp: 'hjh 1/29/2013 18:08'!
titleString

	^'Timer'! !

!LayoutDemo8Timer methodsFor: 'updating' stamp: 'hjh 1/29/2013 18:47'!
wantsSteps
	"Return true if the receiver wants to its #step or #stepAt: methods be run"

	^true! !

!LayoutDemo8Timer class methodsFor: 'as yet unclassified' stamp: 'hjh 2/2/2013 04:19'!
open

	^self new openInWorld ! !
